import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createArrangementDraft, applyArrangementCommand } from "../src/edit/arrangement-editor.js";
import { arrangementDraftPath, loadArrangementDraft, saveArrangementDraft } from "../src/edit/arrangement-draft-persistence.js";
import { bucketsFromPcm16, combineWaveforms, editorStemDisplayLabels, performanceStemDisplayLabels, projectBuckets } from "../src/edit/editor-workspace.js";
import { songId, type PreparedSong } from "../src/domain/song.js";

const song:PreparedSong={song:{id:songId("workspace"),title:"Workspace",artist:"A",vendor:"V",originalKey:"C",originalBpm:120,originalTimeSignature:{numerator:4,denominator:4}},selectedKey:"C",selectedBpm:120,timeSignature:{numerator:4,denominator:4},durationSeconds:4,stems:[{role:"music",sourcePath:"cached.wav",durationSeconds:4}],regions:[{id:"a",name:"A",startSeconds:0,endSeconds:2},{id:"b",name:"B",startSeconds:2,endSeconds:4}],cues:[],cacheFingerprint:"cache"};

test("builds normalized peaks and combines stacked stem shapes",()=>{const bytes=Buffer.alloc(8);[-32768,-1000,1000,32767].forEach((value,index)=>bytes.writeInt16LE(value,index*2));const buckets=bucketsFromPcm16(bytes,2);assert.deepEqual(buckets.map(bucket=>[Number(bucket.min.toFixed(3)),Number(bucket.max.toFixed(3))]),[[-1,-0.031],[0.031,1]]);assert.deepEqual(combineWaveforms([buckets,[{min:-.5,max:.25},{min:-.2,max:.4}]],2),[{min:-1,max:.25},{min:-.2,max:32767/32768}]);});

test("projects source waveform buckets through reordered arrangement sections",()=>{let draft=createArrangementDraft(song);draft=applyArrangementCommand(draft,{type:"move-section",sectionId:"b",toIndex:0});const source=[{min:0,max:.1},{min:0,max:.2},{min:0,max:.7},{min:0,max:.8}];const projected=projectBuckets(source,4,draft);assert.deepEqual(projected.map(bucket=>bucket.max),[.7,.8,.1,.2]);});

test("atomically saves and reloads a valid arrangement draft",async()=>{const root=await mkdtemp(join(tmpdir(),"playback-editor-"));try{const draft=applyArrangementCommand({...createArrangementDraft(song),sourceManifestPath:"source-a",sourceFingerprint:"fingerprint-a",sourceArrangementId:"original-song"},{type:"rename-section",sectionId:"a",name:"Verse 1"}),path=arrangementDraftPath(root,"workspace","original");await saveArrangementDraft(path,draft);assert.deepEqual(await loadArrangementDraft(path,"workspace"),draft);assert.deepEqual(await loadArrangementDraft(path,"workspace",{sourceManifestPath:"source-a",sourceFingerprint:"fingerprint-a",sourceArrangementId:"original-song"}),draft);assert.equal(await loadArrangementDraft(path,"workspace",{sourceManifestPath:"source-b",sourceFingerprint:"fingerprint-a",sourceArrangementId:"original-song"}),null);assert.equal(await loadArrangementDraft(path,"workspace",{sourceManifestPath:"source-a",sourceFingerprint:"fingerprint-b",sourceArrangementId:"original-song"}),null);assert.equal(await loadArrangementDraft(path,"workspace",{sourceManifestPath:"source-a",sourceFingerprint:"fingerprint-a",sourceArrangementId:"other"}),null);assert.equal(await loadArrangementDraft(path,"different"),null);}finally{await rm(root,{recursive:true,force:true});}});
test("derives visible editor labels from original filenames without changing routing roles",()=>{const original={...song,stems:[{role:"music-stem",sourcePath:"C:\\cache\\ACOUSTIC.wav",durationSeconds:4,displayName:"ACOUSTIC"},{role:"music-stem",sourcePath:"C:\\cache\\ELECTRIC_1.wav",durationSeconds:4,displayName:"ELECTRIC_1"}]},rendered={...song,stems:[{role:"music-stem",sourcePath:"01-music-stem.wav",durationSeconds:4},{role:"music-stem",sourcePath:"02-music-stem.wav",durationSeconds:4}]};assert.deepEqual(editorStemDisplayLabels(rendered,original),["ACOUSTIC","ELECTRIC_1"]);assert.deepEqual(editorStemDisplayLabels({...song,stems:[{role:"Elcrectic 2",sourcePath:"x.wav",durationSeconds:4},{role:"Sopranno",sourcePath:"y.wav",durationSeconds:4}]}),["x","y"]);});

test("editor labels prefer source wav names over valid bus roles",()=>{assert.deepEqual(editorStemDisplayLabels({...song,stems:[{role:"electric",sourcePath:"C:\\song\\EG1.wav",durationSeconds:4},{role:"keys",sourcePath:"C:\\song\\KEYS 2.wav",durationSeconds:4}]}),["EG1","KEYS 2"]);});

test("legacy arrangements inherit original stem labels by role occurrence",()=>{const original={...song,stems:[{role:"acoustic",sourcePath:"C:\\song\\ACOUSTIC.wav",durationSeconds:4,displayName:"ACOUSTIC"},{role:"bass",sourcePath:"C:\\song\\BASS.wav",durationSeconds:4,displayName:"BASS"},{role:"drums",sourcePath:"C:\\song\\DRUMS.wav",durationSeconds:4,displayName:"DRUMS"},{role:"electric",sourcePath:"C:\\song\\ELECTRIC_1.wav",durationSeconds:4,displayName:"ELECTRIC_1"},{role:"electric",sourcePath:"C:\\song\\ELECTRIC_2.wav",durationSeconds:4,displayName:"ELECTRIC_2"},{role:"electric",sourcePath:"C:\\song\\ELECTRIC_3.wav",durationSeconds:4,displayName:"ELECTRIC_3"},{role:"keys",sourcePath:"C:\\song\\ORGAN.wav",durationSeconds:4,displayName:"ORGAN"},{role:"keys",sourcePath:"C:\\song\\RHODES.wav",durationSeconds:4,displayName:"RHODES"}]},arrangement={...song,stems:[{role:"Acoustic",sourcePath:"C:\\cache\\01-acoustic.wav",durationSeconds:4},{role:"Electric",sourcePath:"C:\\cache\\04-electric.wav",durationSeconds:4},{role:"Electric",sourcePath:"C:\\cache\\05-electric.wav",durationSeconds:4},{role:"Electric",sourcePath:"C:\\cache\\06-electric.wav",durationSeconds:4},{role:"Bass",sourcePath:"C:\\cache\\02-bass.wav",durationSeconds:4},{role:"Keys",sourcePath:"C:\\cache\\07-keys.wav",durationSeconds:4},{role:"Keys",sourcePath:"C:\\cache\\08-keys.wav",durationSeconds:4},{role:"Drums",sourcePath:"C:\\cache\\03-drums.wav",durationSeconds:4}]};assert.deepEqual(editorStemDisplayLabels(arrangement,original),["ACOUSTIC","ELECTRIC_1","ELECTRIC_2","ELECTRIC_3","BASS","ORGAN","RHODES","DRUMS"]);});

test("performance labels use bus roles instead of original stem filenames",()=>{const prepared={...song,stems:[{role:"electric",sourcePath:"cache/EG1.wav",durationSeconds:4,displayName:"EG1"},{role:"drums",sourcePath:"cache/LOOP.wav",durationSeconds:4,displayName:"LOOP"}]};assert.deepEqual(performanceStemDisplayLabels(prepared),["Electric","Drums"]);});
