import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import type { ConfirmedSetManifest } from "../src/confirmed-set/manifest.js";
import { songId } from "../src/domain/song.js";
import { evaluatePerformanceReadiness } from "../src/live/performance-readiness.js";

async function fixture() {
  const root = await mkdtemp(join(tmpdir(), "playback-ready-")), packageRoot = join(root, "confirmed"); await mkdir(packageRoot);
  const asset = async (name: string) => { const path = join(packageRoot, name); await writeFile(path, name); return path; };
  const music = await asset("music.wav"), waveform = await asset("waveform.json"), click = await asset("click.wav"), cue = await asset("cue.wav"), pad = await asset("pad.wav");
  const song = { song: { id: songId("one"), title: "One", artist: "A", vendor: "V", originalKey: "C", originalBpm: 120, originalTimeSignature: { numerator: 4, denominator: 4 } }, selectedKey: "C", selectedBpm: 120, timeSignature: { numerator: 4, denominator: 4 }, durationSeconds: 8, stems: [{ role: "Music", sourcePath: music, durationSeconds: 8 }], regions: [{ id: "v", name: "Verse", startSeconds: 0, endSeconds: 8 }], cues: [], cacheFingerprint: "hash", waveformPath: waveform, liveAssets: { click: { regularPath: click, accentPath: click, events: [{ atSeconds: 0, accent: true }] }, cues: [{ atSeconds: 0, label: "Verse", audioPath: cue, targetRegionId: "v" }], repeatCuePath: cue, pad: { key: "C", audioPath: pad } } };
  const manifest: ConfirmedSetManifest = { schemaVersion: 1, id: "set", name: "Set", confirmedAt: "now", songs: [song] };
  const native = { deviceOpenMs: 2, armMs: 4, stems: 1, clickEvents: 1, cueEvents: 1, padKey: "C", midiEvents: 0, midiEnabled: false, outputChannels: 6, routingReady: true, stereoFallback: false, nextReady: false, nextIndex: -1 };
  return { root, packageRoot, manifest, native };
}
test("unified performance readiness passes a complete isolated package", async () => { const value = await fixture(); const result = await evaluatePerformanceReadiness({ manifest: value.manifest, manifestPath: join(value.packageRoot, "confirmed-set.json"), songIndex: 0, native: value.native, midiOutputName: null }); assert.equal(result.status, "Ready"); assert.equal(result.ready, true); assert.equal(result.checks.length, 9); });
test("stereo fallback and disabled prepared MIDI warn without blocking audio", async () => { const value = await fixture(); const song = { ...value.manifest.songs[0]!, arrangement: { id: "a", name: "A", sourceType: "reaper-import" as const, sourceSha256: "h", proPresenterMidi: [{ atSeconds: 1, status: 144, data1: 19, data2: 2 }], midiOutputName: null } }; const manifest = { ...value.manifest, songs: [song] }; const result = await evaluatePerformanceReadiness({ manifest, manifestPath: join(value.packageRoot, "confirmed-set.json"), songIndex: 0, native: { ...value.native, outputChannels: 2, routingReady: false, stereoFallback: true, midiEvents: 1 }, midiOutputName: null }); assert.equal(result.status, "Ready with warnings"); assert.equal(result.ready, true); assert.deepEqual(result.checks.filter((item) => item.level === "warning").map((item) => item.id), ["routing", "midi"]); });
test("Original Song control MIDI is counted without arrangement identity", async () => { const value = await fixture(); const song = { ...value.manifest.songs[0]!, control: { sourceType: "reaper-import" as const, sourceSha256: "slides", proPresenterMidi: [{ atSeconds: 1, status: 144, data1: 19, data2: 2 }], midiOutputName: null } }; const manifest = { ...value.manifest, songs: [song] }; const result = await evaluatePerformanceReadiness({ manifest, manifestPath: join(value.packageRoot, "confirmed-set.json"), songIndex: 0, native: { ...value.native, midiEvents: 1, midiEnabled: true }, midiOutputName: "Slides" }); assert.equal(result.status, "Ready"); assert.equal(result.checks.find((item) => item.id === "midi")?.level, "ready"); });
test("media-only setlist items do not require click, cue, pad, MIDI, or regions", async () => { const value = await fixture(); const source = value.manifest.songs[0]!, { liveAssets: _liveAssets, control: _control, arrangement: _arrangement, ...withoutLiveAssets } = source, song = { ...withoutLiveAssets, mediaOnly: true, song: { ...source.song, vendor: "Media" }, selectedKey: "MEDIA", selectedBpm: 120, regions: [], cues: [] }; const manifest = { ...value.manifest, songs: [song] }; const { padKey: _padKey, ...nativeWithoutPad } = value.native; const result = await evaluatePerformanceReadiness({ manifest, manifestPath: join(value.packageRoot, "confirmed-set.json"), songIndex: 0, native: { ...nativeWithoutPad, clickEvents: 0, cueEvents: 0, midiEvents: 0 }, midiOutputName: null }); assert.equal(result.ready, true); assert.equal(result.checks.find((item) => item.id === "structure")?.level, "ready"); assert.equal(result.checks.find((item) => item.id === "engine")?.level, "ready"); });
test("one Reaper measure containing ProPresenter start MIDI is a valid control preroll",async()=>{const value=await fixture(),source=value.manifest.songs[0]!,song={...source,regions:[{...source.regions[0]!,startSeconds:2}],arrangement:{id:"reaper",name:"REAPER · One",sourceType:"reaper-import" as const,sourceSha256:"h",proPresenterMidi:[{atSeconds:0,status:144,data1:1,data2:2}],midiOutputName:"Slides"}},manifest={...value.manifest,songs:[song]};const result=await evaluatePerformanceReadiness({manifest,manifestPath:join(value.packageRoot,"confirmed-set.json"),songIndex:0,native:{...value.native,midiEvents:1,midiEnabled:true},midiOutputName:"Slides"});assert.notEqual(result.checks.find(item=>item.id==="structure")?.level,"blocked");assert.match(result.checks.find(item=>item.id==="structure")!.detail,/measure-and-beat control preroll/);});
test("failure matrix blocks escaped/missing assets, native mismatch, bad routing, and failed next preload", async () => { const value = await fixture(); const outside = join(value.root, "outside.wav"); await writeFile(outside, "outside"); const source = value.manifest.songs[0]!, second = { ...structuredClone(source), song: { ...source.song, id: songId("two"), title: "Two" } }; const broken = { ...source, stems: [{ ...source.stems[0]!, sourcePath: outside }], waveformPath: join(value.packageRoot, "missing.json") }; const manifest = { ...value.manifest, songs: [broken, second] }; const result = await evaluatePerformanceReadiness({ manifest, manifestPath: join(value.packageRoot, "confirmed-set.json"), songIndex: 0, native: { ...value.native, stems: 0, outputChannels: 0, routingReady: false, nextReady: false }, midiOutputName: null }); assert.equal(result.status, "Blocked"); for (const id of ["isolation", "assets", "engine", "routing", "next"]) assert.equal(result.checks.find((item) => item.id === id)?.level, "blocked"); });
test("engine startup failure is represented as a lockable readiness report", async () => { const value = await fixture(); const result = await evaluatePerformanceReadiness({ manifest: value.manifest, manifestPath: join(value.packageRoot, "confirmed-set.json"), songIndex: 0, native: null, midiOutputName: null, nativeError: "Audio device lost" }); assert.equal(result.ready, false); assert.match(result.checks.find((item) => item.id === "engine")!.detail, /Audio device lost/); });
test("Analyzer drafts can load for editing but are blocked from Performance Mode", async () => { const value = await fixture(); const manifest = { ...value.manifest, review: { status: "draft", performanceEligible: false } } as typeof value.manifest; const result = await evaluatePerformanceReadiness({ manifest, manifestPath: join(value.packageRoot, "confirmed-set.json"), songIndex: 0, native: value.native, midiOutputName: null }); assert.equal(result.ready, false); assert.equal(result.checks.find((item) => item.id === "analyzer-review")?.level, "blocked"); });
