import assert from "node:assert/strict";
import test from "node:test";
import type { ConfirmedSetManifest } from "../src/confirmed-set/manifest.js";
import { DEFAULT_ROUTES, PerformanceSession, keyboardAction, validateRoutingPlan, type PerformanceEffects } from "../src/live/performance-session.js";
import type { PerformanceReadinessReport } from "../src/live/performance-readiness.js";
import { songId } from "../src/domain/song.js";
import type { SongTransitionType } from "../src/live/song-transition.js";

const ready:PerformanceReadinessReport={ready:true,status:"Ready",checks:[]};
function setup(readiness:PerformanceReadinessReport=ready,initialSongIndex=0,transition?:SongTransitionType){const calls:string[]=[];const effects:PerformanceEffects={play:()=>calls.push("play"),pause:()=>calls.push("pause"),stop:()=>calls.push("stop"),seek:(x)=>calls.push(`seek:${x}`),panic:()=>calls.push("panic"),announceRecovery:(id,at,repeatAt)=>calls.push(`announce:${id}:${at}:${repeatAt??"none"}`),cancelTransition:()=>calls.push("cancel"),recover:()=>calls.push("recover"),setBus:(bus,on)=>calls.push(`${bus}:${on}`),beginTimedSongTransition:async plan=>{calls.push(`transition:${plan.type}:${plan.toSongIndex}:${plan.durationSeconds}`);},selectSong:async(index)=>{calls.push(`song:${index}`);}};const song=(id:string)=>({song:{id:songId(id),title:id,artist:"A",vendor:"V",originalKey:"C",originalBpm:120,originalTimeSignature:{numerator:4,denominator:4}},selectedKey:"C",selectedBpm:120,timeSignature:{numerator:4,denominator:4},durationSeconds:8,stems:[{role:"music",sourcePath:"cache/a.wav",durationSeconds:8}],regions:[{id:`${id}-v`,name:"Verse",startSeconds:0,endSeconds:4},{id:`${id}-c`,name:"Chorus",startSeconds:4,endSeconds:8}],cues:[],cacheFingerprint:"hash",liveAssets:{click:{regularPath:"r",accentPath:"a",events:[{atSeconds:0,accent:true}]},repeatCuePath:"repeat",cues:[{atSeconds:0,label:"Start",audioPath:"c",targetRegionId:`${id}-v`},{atSeconds:3,label:"Chorus",audioPath:"c",targetRegionId:`${id}-c`}],pad:{key:"C",audioPath:"p"}}});const manifest:ConfirmedSetManifest={schemaVersion:1,id:"set",name:"Set",confirmedAt:"now",songs:[song("one"),song("two")],...(transition?{transitions:[{fromSongIndex:0,toSongIndex:1,type:transition,durationSeconds:transition==="crossfade"||transition==="overlap"?5:0,continuePad:true}]}:{})};return{calls,session:new PerformanceSession(manifest,effects,DEFAULT_ROUTES,readiness,undefined,initialSongIndex)};}
test("jumps announce at the cue marker before moving at the boundary",()=>{const{calls,session}=setup();session.play();session.updatePosition(1.2);session.jumpToRegion("one-c");assert.equal(session.snapshot.recoveryCueAtSeconds,3);assert.equal(session.snapshot.recoverAtSeconds,4);session.updatePosition(3.9);assert.equal(session.snapshot.positionSeconds,3.9);session.updatePosition(4);assert.equal(session.snapshot.positionSeconds,4);assert.deepEqual(calls,["play","announce:one-c:3:none","seek:4","recover"]);});
test("loops say Repeat two beats before the section announcement",()=>{const{calls,session}=setup();session.play();session.updatePosition(4.2);session.toggleLoop("one-c");assert.equal(session.snapshot.recoveryCueAtSeconds,7);session.updatePosition(8);assert.equal(session.snapshot.positionSeconds,4);assert.equal(session.snapshot.loopRegionId,"one-c");assert.equal(session.snapshot.recoveryCueAtSeconds,7);assert.deepEqual(calls,["play","announce:one-c:7:6","seek:4","recover","announce:one-c:7:6"]);});
test("Repeat Once announces, returns once, and does not become a loop",()=>{const{calls,session}=setup();session.play();session.updatePosition(4.2);session.repeatOnce("one-c");assert.equal(session.snapshot.loopRegionId,null);assert.equal(session.snapshot.recoveryCueAtSeconds,7);session.updatePosition(8);assert.equal(session.snapshot.positionSeconds,4);assert.equal(session.snapshot.recoveryRegionId,null);session.updatePosition(8);assert.equal(session.snapshot.positionSeconds,8);assert.deepEqual(calls,["play","announce:one-c:7:6","seek:4","recover"]);});
test("loop cancellation restores normal cues before Repeat and locks afterward",()=>{const early=setup();early.session.play();early.session.updatePosition(4.5);early.session.toggleLoop("one-c");early.session.updatePosition(5.9);early.session.toggleLoop("one-c");assert.equal(early.session.snapshot.loopRegionId,null);assert.ok(early.calls.includes("cancel"));const late=setup();late.session.play();late.session.updatePosition(4.5);late.session.toggleLoop("one-c");late.session.updatePosition(6);assert.throws(()=>late.session.toggleLoop("one-c"),/locked/);assert.equal(late.session.snapshot.loopRegionId,"one-c");});
test("panic announces at the cue marker and recovers at the later section boundary",()=>{const{calls,session}=setup();session.play();session.updatePosition(1.2);session.panic();assert.equal(session.snapshot.playing,true);assert.equal(session.snapshot.panicActive,true);assert.equal(session.snapshot.channels.click,true);assert.equal(session.snapshot.channels.pad,true);session.armRecovery("one-c");assert.equal(session.snapshot.recoveryCueAtSeconds,3);assert.equal(session.snapshot.recoverAtSeconds,4);session.updatePosition(3.99);assert.equal(session.snapshot.panicActive,true);session.updatePosition(4);assert.equal(session.snapshot.panicActive,false);assert.equal(session.snapshot.positionSeconds,4);assert.equal(session.snapshot.channels.pad,false);assert.deepEqual(calls,["play","panic","announce:one-c:3:none","seek:4","recover"]);});

test("panic defers a recovery boundary when the full cue lead has already passed",()=>{const{calls,session}=setup();session.play();session.updatePosition(3.5);session.panic();session.armRecovery("one-c");assert.equal(session.snapshot.recoveryCueAtSeconds,7);assert.equal(session.snapshot.recoverAtSeconds,8);assert.ok(calls.includes("announce:one-c:7:none"));});
test("native faults remain separate from musical panic",()=>{const{session}=setup();session.reportFault("Audio device lost");assert.equal(session.snapshot.fault,"Audio device lost");assert.equal(session.snapshot.panicActive,false);assert.throws(()=>session.play(),/Clear panic or fault/);});
test("song changes are stopped and armed through one safe transition",async()=>{const{calls,session}=setup();await session.selectSong(1);assert.equal(session.snapshot.songIndex,1);assert.equal(session.snapshot.currentRegionId,"two-v");assert.deepEqual(calls,["stop","song:1"]);});
test("Cue Next finishes by selecting the next song without playing it",async()=>{const{calls,session}=setup(ready,0,"cue-next");session.play();session.updatePosition(8);await new Promise(resolve=>setImmediate(resolve));assert.equal(session.snapshot.songIndex,1);assert.equal(session.snapshot.playing,false);assert.deepEqual(calls,["play","stop","song:1","pad:true"]);});
test("Stay finishes without changing the selected song",async()=>{const{calls,session}=setup(ready,0,"stay-in-song");session.play();session.updatePosition(8);await new Promise(resolve=>setImmediate(resolve));assert.equal(session.snapshot.songIndex,0);assert.equal(session.snapshot.playing,false);assert.deepEqual(calls,["play","stop"]);});
test("a song without a following transition stops and clamps at its prepared duration",()=>{const{session}=setup();session.play();session.updatePosition(9.5);assert.equal(session.snapshot.positionSeconds,8);assert.equal(session.snapshot.playing,false);assert.equal(session.snapshot.currentRegionId,"one-c");});
test("AutoLink selects and immediately starts the next song",async()=>{const{calls,session}=setup(ready,0,"auto-link");session.play();session.updatePosition(8);await new Promise(resolve=>setImmediate(resolve));assert.equal(session.snapshot.songIndex,1);assert.equal(session.snapshot.playing,true);assert.deepEqual(calls,["play","stop","song:1","pad:true","play"]);});
test("Overlap and Crossfade arm distinct timed engine transitions before song end",async()=>{for(const type of ["overlap","crossfade"] as const){const{calls,session}=setup(ready,0,type);session.play();session.updatePosition(2.98);assert.equal(calls.some(call=>call.startsWith("transition:")),false);session.updatePosition(3);await new Promise(resolve=>setImmediate(resolve));assert.ok(calls.includes(`transition:${type}:1:5`));assert.equal(session.snapshot.songIndex,1);assert.equal(session.snapshot.playing,true);}});
test("a Performance transition change replaces the live plan immediately",async()=>{const{calls,session}=setup(ready,0,"stay-in-song");session.setTransitionPlan({fromSongIndex:0,toSongIndex:1,type:"auto-link",durationSeconds:0,continuePad:true});session.play();session.updatePosition(8);await new Promise(resolve=>setImmediate(resolve));assert.equal(session.snapshot.songIndex,1);assert.equal(session.snapshot.playing,true);assert.deepEqual(calls,["play","stop","song:1","pad:true","play"]);});
test("a persisted set-card selection initializes the matching song workspace",()=>{const{session}=setup(ready,1);assert.equal(session.snapshot.songIndex,1);assert.equal(session.snapshot.currentRegionId,"two-v");assert.equal(session.song.song.title,"two");});
test("Cue Next selects the prearmed song, enables its pad, and does not start it",async()=>{const{calls,session}=setup();session.play();await session.cueNext();assert.equal(session.snapshot.songIndex,1);assert.equal(session.snapshot.playing,false);assert.equal(session.snapshot.channels.pad,true);assert.deepEqual(calls,["play","stop","song:1","pad:true"]);});
test("mixer exposes every stem and live source with independent switches and master gain",()=>{const{session}=setup();assert.deepEqual(session.snapshot.mixer.channels.map(channel=>channel.kind),["stem","click","cue","pad"]);session.setMixerChannel(0,{gain:.62,muted:true,solo:true,iem:true});session.setMasterGain(.8);assert.deepEqual(session.snapshot.mixer.channels[0],{id:"stem-0",index:0,kind:"stem",gain:.62,muted:true,solo:true,iem:true});assert.equal(session.snapshot.mixer.masterGain,.8);assert.throws(()=>session.setMixerChannel(9,{gain:1}),/outside/);});
test("routing rejects collisions and keyboard actions are deterministic",()=>{validateRoutingPlan(DEFAULT_ROUTES);assert.throws(()=>validateRoutingPlan({...DEFAULT_ROUTES,cue:{firstOutput:1,channels:1}}),/assigned more than once/);assert.equal(keyboardAction(" "),"play-pause");assert.equal(keyboardAction("Escape"),"panic");assert.equal(keyboardAction("l"),"loop");assert.equal(keyboardAction("r"),null);assert.equal(keyboardAction("x"),null);});
test("blocked readiness locks performance controls but always permits Stop",()=>{const blocked:PerformanceReadinessReport={ready:false,status:"Blocked",checks:[{id:"assets",label:"Assets",level:"blocked",detail:"missing"}]};const{calls,session}=setup(blocked);assert.throws(()=>session.play(),/not ready/);session.stop();assert.deepEqual(calls,["stop"]);});
test("a newly blocked readiness report safely stops active playback",()=>{const{calls,session}=setup();session.play();session.setReadiness({ready:false,status:"Blocked",checks:[]});assert.equal(session.snapshot.playing,false);assert.equal(session.snapshot.ready,false);assert.deepEqual(calls,["play","stop"]);});
