const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("playback", {
  bootstrap: () => ipcRenderer.invoke("playback:bootstrap"),
  command: (command, value) => ipcRenderer.send("playback:command", command, value),
  onTransport: (listener) => ipcRenderer.on("playback:transport", (_event, state) => listener(state)),
  windows: { onMenuAction:(listener)=>ipcRenderer.on("windows:menu",(_event,action)=>listener(action)) },
  performance: { get:()=>ipcRenderer.invoke("performance:get"), command:(value)=>ipcRenderer.invoke("performance:command",value), saveMix:()=>ipcRenderer.invoke("performance:save-mix"), onState:(listener)=>ipcRenderer.on("performance:state",(_event,state)=>listener(state)), onMeters:(listener)=>ipcRenderer.on("mixer:meters",(_event,meters)=>listener(meters)) },
  set: { getSong:(index)=>ipcRenderer.invoke("set:get-song",index), selectSong:(index)=>ipcRenderer.invoke("set:select-song",index) },
  arrangements: { previewReaper:()=>ipcRenderer.invoke("reaper:preview"), commitReaper:(action)=>ipcRenderer.invoke("reaper:commit",action) },
  midi: { setOutput:(name)=>ipcRenderer.invoke("midi:set-output",name) },
  audio: { setDevice:(device)=>ipcRenderer.invoke("audio:set-device",device), setRouting:(routing)=>ipcRenderer.invoke("audio:set-routing",routing), setGlobalBusRouting:(routing)=>ipcRenderer.invoke("audio:set-global-bus-routing",routing), setGlobalBusRoutingLock:(locked)=>ipcRenderer.invoke("audio:set-global-bus-routing-lock",locked), refresh:()=>ipcRenderer.invoke("audio:refresh"), onHealth:(listener)=>ipcRenderer.on("audio:health",(_event,state)=>listener(state)) },
  clickSounds: { get:()=>ipcRenderer.invoke("click-sounds:get"), choose:(kind)=>ipcRenderer.invoke("click-sounds:choose",kind), reset:()=>ipcRenderer.invoke("click-sounds:reset"), preview:(kind)=>ipcRenderer.invoke("click-sounds:preview",kind) },
  transitions: { get:()=>ipcRenderer.invoke("transitions:get"), set:(settings)=>ipcRenderer.invoke("transitions:set",settings) },
  prep: { get:()=>ipcRenderer.invoke("prep:get"),status:()=>ipcRenderer.invoke("prep:status"),update:()=>ipcRenderer.invoke("prep:update"),review:(songId)=>ipcRenderer.invoke("prep:review",songId),command:(command)=>ipcRenderer.invoke("prep:command",command),loadItem:(itemId)=>ipcRenderer.invoke("prep:load-item",itemId),confirm:(options)=>ipcRenderer.invoke("prep:confirm",options),exportSetlist:()=>ipcRenderer.invoke("prep:export-setlist"),importSetlist:()=>ipcRenderer.invoke("prep:import-setlist"),onStatus:(listener)=>ipcRenderer.on("prep:status",(_event,state)=>listener(state)),onLoadStatus:(listener)=>ipcRenderer.on("editor:load-status",(_event,state)=>listener(state)),onWaveformsReady:(listener)=>ipcRenderer.on("editor:waveforms-ready",(_event,state)=>listener(state)),onConfirmStatus:(listener)=>ipcRenderer.on("prep:confirm-status",(_event,state)=>listener(state)) },
  control: { get:()=>ipcRenderer.invoke("control:get"),command:(command)=>ipcRenderer.invoke("control:command",command),setSettings:(settings)=>ipcRenderer.invoke("control:set-settings",settings),setMidiInput:(settings)=>ipcRenderer.invoke("control:set-midi-input",settings),gldPreview:(settings)=>ipcRenderer.invoke("control:gld-preview",settings),gldTest:(settings)=>ipcRenderer.invoke("control:gld-test",settings),onState:(listener)=>ipcRenderer.on("control:state",(_event,state)=>listener(state)),onMidiInput:(listener)=>ipcRenderer.on("control:midi-input",(_event,state)=>listener(state)) },
  arrange: { get:()=>ipcRenderer.invoke("arrange:get"),workspace:()=>ipcRenderer.invoke("arrange:workspace"),command:(command)=>ipcRenderer.invoke("arrange:command",command),undo:()=>ipcRenderer.invoke("arrange:undo"),redo:()=>ipcRenderer.invoke("arrange:redo"),saveDraft:()=>ipcRenderer.invoke("arrange:save-draft"),revert:()=>ipcRenderer.invoke("arrange:revert"),auditionCue:(cueId)=>ipcRenderer.invoke("arrange:audition-cue",cueId),save:()=>ipcRenderer.invoke("arrange:save") },
  editor: {
    get: () => ipcRenderer.invoke("editor:get"),
    command: (command) => ipcRenderer.invoke("editor:command", command),
    mixerChannel: (channel) => ipcRenderer.invoke("editor:mixer-channel", channel),
    undo: () => ipcRenderer.invoke("editor:undo"), redo: () => ipcRenderer.invoke("editor:redo"),
    save: () => ipcRenderer.invoke("editor:save"), approve: () => ipcRenderer.invoke("editor:approve"),
    auditionCue: (cueId) => ipcRenderer.invoke("editor:audition-cue", cueId),
  },
});
