export const REMOTE_CONTROL_PAGE = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#081018">
<title>Playback V3 Remote</title>
<style>
:root{color-scheme:dark;font-family:Inter,"Segoe UI",system-ui,sans-serif;background:#070b10;color:#edf6fc}
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:linear-gradient(180deg,#0d1823,#05080d 54%);overscroll-behavior:none;touch-action:manipulation}
button{font:inherit;touch-action:manipulation}
header{position:sticky;top:0;z-index:30;display:grid;grid-template-columns:1fr auto auto;gap:12px;align-items:center;padding:10px 14px;border-bottom:1px solid #223442;background:#091018f7;backdrop-filter:blur(12px)}
.brand{display:grid;gap:2px}.brand span,.label{color:#63d8ff;font-size:8px;font-weight:900;letter-spacing:.16em;text-transform:uppercase}.brand strong{font-size:17px}
.status{padding:7px 11px;border:1px solid #27775c;border-radius:99px;background:#102a21;color:#78efb7;font-size:9px;font-weight:900;letter-spacing:.08em}.status.off{border-color:#79333e;background:#32141a;color:#ff8798}
.transport-mini{display:flex;gap:7px}.transport-mini button{min-width:48px;min-height:42px;border:1px solid #364b5a;border-radius:8px;background:#14212b;color:#eef8fd;font-weight:900}.transport-mini .play{min-width:62px;background:#48c7ee;color:#041018}.transport-mini .panic{border-color:#7e3340;background:#34141a;color:#ff9aaa}.transport-mini .panic.active{background:#bd3047;color:#fff;box-shadow:0 0 15px #ff526f88}
main{display:grid;grid-template-rows:auto auto minmax(280px,1fr) auto;gap:10px;min-height:calc(100vh - 64px);padding:10px}
.set-deck{display:flex;min-width:0;height:92px;border:2px solid #31485a;border-radius:10px;background:#081018;overflow-x:auto;scrollbar-width:thin}
.set-label{display:grid;min-width:126px;place-content:center;padding:10px;border-right:1px solid #304453;background:#101c25}.set-label span{color:#6c8495;font-size:7px;font-weight:900;letter-spacing:.13em}.set-label strong{max-width:110px;margin-top:4px;overflow:hidden;font-size:11px;text-overflow:ellipsis;white-space:nowrap}
.set-songs{display:flex;min-width:max-content;flex:1;gap:4px;padding:4px}.song-card{display:grid;width:165px;grid-template-columns:24px 1fr;grid-template-rows:1fr auto;gap:3px 7px;padding:9px;border:2px solid #2e4657;border-radius:7px;background:#101c25;color:#f2f8fb;text-align:left}.song-card b{grid-row:1/3;align-self:center;color:#7e99aa;font-size:10px}.song-card strong,.song-card small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.song-card strong{align-self:end;font-size:12px}.song-card small{color:#8ca3b2;font-size:8px}.song-card.active{border-color:#b68cff;background:#1f293c;box-shadow:inset 0 -4px #b68cff}.song-card.active b{color:#b68cff}
.transition{display:grid;width:72px;place-content:center;gap:3px;border:1px solid #684d80;border-radius:8px;background:#1d1428;color:#e7d7f6;text-align:center}.transition span{color:#a98fc2;font-size:6px;font-weight:900;letter-spacing:.08em}.transition strong{max-width:62px;overflow:hidden;font-size:7px;text-overflow:ellipsis;white-space:nowrap}
.now-bar{display:grid;grid-template-columns:minmax(180px,1fr) auto minmax(180px,1fr);gap:10px;align-items:center;padding:10px 12px;border:1px solid #263b4c;border-radius:10px;background:#0c151d}.now-card{display:grid;gap:3px}.now-card span{color:#6f8696;font-size:7px;font-weight:900;letter-spacing:.14em}.now-card strong{font-size:clamp(16px,2.7vw,27px)}.now-card small{color:#8ba1af;font-size:10px}.clock{text-align:center}.clock span{color:#7f95a3;font-size:7px;font-weight:900;letter-spacing:.13em}.clock strong{display:block;font:900 clamp(20px,4vw,34px)/1.1 ui-monospace,"Cascadia Mono",monospace}.clock small{display:block;margin-top:5px;color:#b7c7d1;font-size:11px}.action-row{display:flex;justify-content:flex-end;gap:7px}.action-row button{min-height:48px;min-width:82px;border:1px solid #3c5263;border-radius:8px;background:#14212b;color:#f2f8fb;font-weight:900;font-size:11px}.action-row button.active{background:#234f3f;border-color:#45c993;color:#95ffd0}
.timeline-card{position:relative;display:grid;grid-template-rows:28px 30px minmax(180px,1fr) 48px;border:2px solid #31495a;border-radius:12px;background:#090f15;overflow:hidden}
.ruler,.cue-lane,.region-lane,.wave-wrap{position:relative}.ruler{border-bottom:1px solid #263846;background:#0d151d;color:#7d93a1}.ruler i,.cue-lane i,.region-block,.grid-line{position:absolute}.ruler i{top:0;height:100%;border-left:1px solid #3a4c59}.ruler span{position:absolute;top:7px;left:4px;font-size:8px;white-space:nowrap}.cue-lane{border-bottom:1px solid #21313d;background:#0a1118}.cue-lane i{top:5px;width:8px;height:20px;transform:translateX(-4px);border-radius:3px;background:#ffc04f;box-shadow:0 0 8px #ffc04f99}.cue-lane i span{position:absolute;left:9px;top:-2px;max-width:82px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border-radius:5px;padding:3px 5px;background:#4b3711;color:#fff0b8;font-size:8px;font-weight:900}
.wave-wrap{overflow:hidden;background:repeating-linear-gradient(90deg,#ffffff07 0,#ffffff07 1px,transparent 1px,transparent 2.5%);touch-action:none}.wave-wrap canvas{position:absolute;inset:0;width:100%;height:100%}.region-layer{position:absolute;inset:0}.region-block{top:0;bottom:0;border-left:2px solid #ef4444;border-right:1px solid #ffffff22;background:color-mix(in srgb,var(--region,#48545f) 25%,transparent);overflow:hidden}.region-block.current{background:color-mix(in srgb,var(--region,#48545f) 45%,transparent);box-shadow:inset 0 0 0 2px #ffffff22}.region-block.selected{outline:2px solid #ffcf5c;outline-offset:-3px}.region-block strong{position:absolute;left:7px;top:9px;max-width:calc(100% - 10px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border-radius:5px;padding:5px 7px;background:#000a;color:#fff;font-size:10px}.region-block small{position:absolute;left:7px;top:38px;color:#cbd6dc;font-size:8px}
.playhead{position:absolute;top:0;bottom:0;left:0;z-index:8;width:3px;background:#ffcf5c;box-shadow:0 0 10px #ffcf5c;pointer-events:none}.playhead:before{content:"";position:absolute;top:0;left:-5px;border:7px solid transparent;border-top-color:#ffcf5c}
.timeline-footer{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 12px;border-top:1px solid #263846;background:#0c151d}.timeline-footer strong{color:#ffcf5c;font-size:12px}.timeline-footer span{color:#91a7b5;font-size:10px}.timeline-footer button{min-height:32px;border:1px solid #3b5060;border-radius:7px;background:#14212b;color:#f4fbff;font-weight:900;font-size:10px}
.hint{min-height:36px;margin:0;padding:10px 12px;border:1px solid #2c3e4b;border-radius:7px;background:#0b141b;color:#8fa6b5;font-size:10px}.hint.error{border-color:#79333e;color:#ff8798}
.verse{--region:#0077cc}.chorus{--region:#cc004e}.bridge{--region:#7600cc}.pre-chorus{--region:#cc298b}.tag{--region:#cc2929}.intro{--region:#b3a724}.ending{--region:#998f1f}.end{--region:#998f1f}.outro{--region:#7e7619}.interlude,.turnaround,.vamp{--region:#20af54}.instrumental{--region:#8a0f88}.breakdown{--region:#bb6b21}
@media(max-width:900px){header{grid-template-columns:1fr auto}.transport-mini{grid-column:1/3;width:100%;display:grid;grid-template-columns:repeat(5,1fr)}.now-bar{grid-template-columns:1fr}.action-row{display:grid;grid-template-columns:repeat(4,1fr)}.action-row button{min-width:0}.set-label{display:none}.timeline-card{grid-template-rows:26px 28px minmax(220px,1fr) 48px}.song-card{width:145px}}
@media(max-width:560px){main{padding:7px}.set-deck{height:78px}.song-card{width:128px}.transition{width:58px}.now-card strong{font-size:17px}.clock strong{font-size:23px}.action-row button{font-size:9px;padding:0 5px}.region-block strong{font-size:9px}}
</style>
</head>
<body>
<header>
  <div class="brand"><span>PLAYBACK V3</span><strong>Performance Remote</strong></div>
  <span id="status" class="status off">OFFLINE</span>
  <div class="transport-mini">
    <button data-command="transport.stop">STOP</button>
    <button class="play" data-command="transport.play">PLAY</button>
    <button data-command="transport.pause">PAUSE</button>
    <button id="pad">PAD</button>
    <button id="panic" class="panic" data-command="panic.enter">PANIC</button>
  </div>
</header>
<main>
  <section class="set-deck"><div class="set-label"><span>CONFIRMED SET</span><strong id="set">Connecting...</strong></div><div id="setSongs" class="set-songs"></div></section>
  <section class="now-bar">
    <article class="now-card"><span>NOW PLAYING</span><strong id="song">Connecting...</strong><small id="section">No section</small></article>
    <div class="clock"><span>ELAPSED / REMAINING</span><strong id="clock">0:00.000 / -0:00.000</strong><small id="songFacts">No song armed</small></div>
    <div class="action-row"><button data-command="section.previous">PREV</button><button data-command="section.next">NEXT</button><button data-command="song.cue-next">CUE NEXT</button><button id="loop">LOOP</button><button id="repeat">REPEAT</button></div>
  </section>
  <section class="timeline-card">
    <div id="ruler" class="ruler"></div>
    <div id="cueLane" class="cue-lane"></div>
    <div id="waveWrap" class="wave-wrap"><canvas id="wave"></canvas><div id="regionLayer" class="region-layer"></div><i id="playhead" class="playhead"></i></div>
    <footer class="timeline-footer"><strong id="touchPosition">1.1</strong><span id="touchHint">Drag or tap the waveform to move the playhead. Tap a region to select. Double-tap a region to jump.</span><button id="centerPlayhead">CENTER</button></footer>
  </section>
  <p id="hint" class="hint">Remote mirrors Performance Mode controls for stage use.</p>
</main>
<script>
const token=new URLSearchParams(location.search).get('token')||'',headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};
let state=null,selected=null,lastTap={id:null,at:0},waveform={key:'',buckets:[],durationSeconds:1,loading:false,error:''},dragging=false,lastSeekAt=0;
const $=id=>document.getElementById(id);
async function command(value){try{const response=await fetch('/api/command',{method:'POST',headers,body:JSON.stringify(value)}),result=await response.json();if(!response.ok)throw Error(result.error||'Command rejected');return result}catch(error){$('hint').textContent=error.message;$('hint').classList.add('error')}}
document.querySelectorAll('[data-command]').forEach(button=>button.onclick=()=>command({type:button.dataset.command}));
$('loop').onclick=()=>selected?command({type:'section.loop',regionId:selected}):hint('Select a region before enabling Loop.');
$('repeat').onclick=()=>selected?command({type:'section.repeat-once',regionId:selected}):hint('Select the region to repeat once.');
$('pad').onclick=()=>command({type:'bus.set',bus:'pad',enabled:!(state&&state.performance.channels.pad)});
$('centerPlayhead').onclick=()=>scrollPlayheadIntoView();
function hint(message){$('hint').textContent=message;$('hint').classList.remove('error')}
function choose(region){const now=Date.now(),panic=state.performance.panicActive;if(panic){selected=region.id;command({type:'panic.recover',regionId:region.id});hint('Recovery armed for '+region.name)}else{selected=region.id;if(lastTap.id===region.id&&now-lastTap.at<550){command({type:'section.jump',regionId:region.id});hint('Jump armed for '+region.name);lastTap={id:null,at:0}}else{lastTap={id:region.id,at:now};hint(state.performance.playing?'Tap again to jump to '+region.name:'Selected '+region.name)}}render(state)}
function seekFromPointer(event,commit){const song=currentSong();if(!song)return;const rect=$('waveWrap').getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),seconds=ratio*song.durationSeconds;$('touchPosition').textContent=gridTime(seconds,song);if(commit||Date.now()-lastSeekAt>90){lastSeekAt=Date.now();command({type:'transport.seek',seconds})}}
$('waveWrap').onpointerdown=event=>{if(event.target.closest('.region-block'))return;dragging=true;$('waveWrap').setPointerCapture(event.pointerId);seekFromPointer(event,true)};
$('waveWrap').onpointermove=event=>{if(dragging)seekFromPointer(event,false)};
$('waveWrap').onpointerup=event=>{if(!$('waveWrap').hasPointerCapture(event.pointerId))return;$('waveWrap').releasePointerCapture(event.pointerId);dragging=false;seekFromPointer(event,true)};
$('waveWrap').onpointercancel=()=>{dragging=false};
function render(next){state=next;const p=next.performance,song=next.songs[p.songIndex],current=song&&song.regions.find(region=>region.id===p.currentRegionId),duration=song?Math.max(.001,song.durationSeconds):1,position=Math.min(duration,Math.max(0,p.positionSeconds));$('set').textContent=next.setName;$('song').textContent=song?song.title:'No song armed';$('section').textContent=current?current.name:'No section';$('clock').textContent=format(position)+' / -'+format(Math.max(0,duration-position));$('songFacts').textContent=song?song.arrangement+' | '+song.key+' | '+song.bpm+' BPM':'No song armed';$('status').textContent=p.ready?'READY':'BLOCKED';$('status').classList.toggle('off',!p.ready);$('panic').textContent=p.panicActive?'PANIC ACTIVE':'PANIC';$('panic').classList.toggle('active',p.panicActive);$('pad').textContent=song?'PAD '+song.key:'PAD';$('pad').classList.toggle('active',!!p.channels.pad);$('loop').classList.toggle('active',!!p.loopRegionId);$('repeat').classList.toggle('active',!!p.recoveryRegionId&&!p.loopRegionId);$('playhead').style.left=(position/duration*100)+'%';$('touchPosition').textContent=gridTime(position,song);renderSet(next);renderTimeline(song,p);loadWaveform(song);drawWaveform()}
function renderSet(next){const p=next.performance,children=[];next.songs.forEach((song,index)=>{if(index){const transition=next.transitions.find(item=>item.fromSongIndex===index-1),card=document.createElement('div');card.className='transition';card.innerHTML='<span>TRANSITION</span><strong>'+escapeHtml(transition?transitionName(transition.type):'CUE NEXT')+'</strong>';children.push(card)}const button=document.createElement('button');button.className='song-card'+(index===p.songIndex?' active':'');button.innerHTML='<b>'+String(index+1).padStart(2,'0')+'</b><strong>'+escapeHtml(song.title)+'</strong><small>'+escapeHtml(song.key)+' | '+song.bpm+' BPM</small>';button.onclick=()=>command({type:'song.select',index});children.push(button)});$('setSongs').replaceChildren(...children)}
function renderTimeline(song,p){$('ruler').replaceChildren();$('cueLane').replaceChildren();$('regionLayer').replaceChildren();if(!song)return;const duration=Math.max(.001,song.durationSeconds);for(let i=0;i<=10;i++){const mark=document.createElement('i'),label=document.createElement('span'),seconds=duration*i/10;mark.style.left=(i*10)+'%';label.style.left=(i*10)+'%';label.textContent=gridTime(seconds,song);$('ruler').append(mark,label)}for(const cue of song.cues||[]){const marker=document.createElement('i');marker.style.left=(cue.atSeconds/duration*100)+'%';marker.title=cue.phrase+' '+positionLabel(cue.position);marker.innerHTML='<span>'+escapeHtml(cue.phrase)+'</span>';$('cueLane').append(marker)}for(const region of song.regions){const block=document.createElement('button'),left=region.startSeconds/duration*100,width=Math.max(.25,(region.endSeconds-region.startSeconds)/duration*100);block.className='region-block '+regionClass(region.name)+(region.id===p.currentRegionId?' current':'')+(region.id===selected?' selected':'');block.style.left=left+'%';block.style.width=width+'%';block.innerHTML='<strong>'+escapeHtml(region.name)+'</strong><small>'+positionLabel(region.startPosition,gridTime(region.startSeconds,song))+'</small>';block.onclick=event=>{event.stopPropagation();choose(region)};$('regionLayer').append(block)}}
async function loadWaveform(song){if(!song)return;const key=(song.waveformPath||'')+'|'+song.index+'|'+song.durationSeconds;if(waveform.key===key)return;waveform={key,buckets:[],durationSeconds:song.durationSeconds,loading:true,error:''};drawWaveform();try{const response=await fetch('/api/waveform?index='+song.index,{headers}),data=await response.json();if(!response.ok)throw Error(data.error||'Waveform unavailable');waveform={key,buckets:Array.isArray(data.buckets)?data.buckets:[],durationSeconds:Number(data.durationSeconds)||song.durationSeconds,loading:false,error:''};drawWaveform()}catch(error){waveform={key,buckets:[],durationSeconds:song.durationSeconds,loading:false,error:error.message||'Waveform unavailable'};drawWaveform()}}
function drawWaveform(){const canvas=$('wave'),rect=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(rect.width*scale));canvas.height=Math.max(1,Math.floor(rect.height*scale));const context=canvas.getContext('2d');context.setTransform(scale,0,0,scale,0,0);context.clearRect(0,0,rect.width,rect.height);const mid=rect.height/2,buckets=waveform.buckets;if(!buckets.length){context.strokeStyle='#63d8ff55';context.lineWidth=2;context.beginPath();context.moveTo(0,mid);context.lineTo(rect.width,mid);context.stroke();context.fillStyle=waveform.error?'#ff8798':'#91a7b5';context.font='900 11px Inter,Segoe UI,sans-serif';context.textAlign='center';context.fillText(waveform.loading?'LOADING WAVEFORM':(waveform.error||'WAVEFORM NOT PREPARED'),rect.width/2,mid-12);return}const magnitudes=buckets.map(bucket=>Math.max(Math.abs(Number(bucket.min)||0),Math.abs(Number(bucket.max)||0))).sort((a,b)=>a-b),reference=magnitudes[Math.min(magnitudes.length-1,Math.floor(magnitudes.length*.985))]||1,gain=Math.max(1,Math.min(12,.92/Math.max(.02,reference)));context.strokeStyle='#63d8ff';context.lineWidth=Math.max(1,rect.width/buckets.length);context.shadowColor='#63d8ff';context.shadowBlur=3;context.globalAlpha=.94;context.beginPath();for(let index=0;index<buckets.length;index++){const bucket=buckets[index],x=index/buckets.length*rect.width,min=Math.max(-1,Math.min(1,(Number(bucket.min)||0)*gain)),max=Math.max(-1,Math.min(1,(Number(bucket.max)||0)*gain));context.moveTo(x,mid+min*mid*.84);context.lineTo(x,mid+max*mid*.84)}context.stroke();context.shadowBlur=0;context.globalAlpha=.2;context.lineWidth=1;context.beginPath();context.moveTo(0,Math.round(mid)+.5);context.lineTo(rect.width,Math.round(mid)+.5);context.stroke()}
function scrollPlayheadIntoView(){const wrap=$('waveWrap'),head=$('playhead').getBoundingClientRect(),box=wrap.getBoundingClientRect();if(head.left<box.left||head.right>box.right)wrap.scrollLeft+=head.left-box.left-box.width*.45}
function currentSong(){return state&&state.songs[state.performance.songIndex]}
function transitionName(value){return({'cue-next':'CUE NEXT','stay-in-song':'STAY','auto-link':'AUTO LINK',overlap:'OVERLAP',crossfade:'CROSSFADE'})[value]||String(value).toUpperCase()}
function regionClass(name){const value=String(name).toLowerCase().replace(/[_-]+/g,' ');if(value.includes('pre chorus')||value.includes('prechorus'))return'pre-chorus';for(const type of['chorus','verse','bridge','instrumental','turnaround','interlude','breakdown','vamp','outro','intro','tag','ending','end'])if(value.includes(type))return type;return'other'}
function gridTime(seconds,song){if(!song)return'1.1';const meter=song.timeSignature||{numerator:4},perMeasure=Math.max(1,Number(meter.numerator)||4),anchors=gridAnchors(song);if(anchors.length){let previous=anchors[0],next=anchors[anchors.length-1];for(const anchor of anchors){if(anchor.seconds<=seconds+.0001)previous=anchor;if(anchor.seconds>=seconds-.0001){next=anchor;break}}let gridBeat=previous.gridBeat;if(next.seconds>previous.seconds)gridBeat=previous.gridBeat+(next.gridBeat-previous.gridBeat)*Math.max(0,Math.min(1,(seconds-previous.seconds)/(next.seconds-previous.seconds)));else if(seconds>previous.seconds&&song.durationSeconds>previous.seconds){const tailBeats=Math.max(0,next.gridBeat-previous.gridBeat)||Math.max(1,perMeasure);gridBeat=previous.gridBeat+((seconds-previous.seconds)/Math.max(.001,song.durationSeconds-previous.seconds))*tailBeats}return gridBeatLabel(gridBeat,perMeasure)}const beatSeconds=60/Math.max(1,Number(song.bpm)||120),total=Math.max(0,Math.round(seconds/beatSeconds));return Math.floor(total/perMeasure)+1+'.'+(total%perMeasure+1)}
function gridAnchors(song){const anchors=[];for(const region of song.regions||[]){addAnchor(anchors,region.startSeconds,region.startPosition,song.timeSignature);addAnchor(anchors,region.endSeconds,region.endPosition,song.timeSignature)}for(const cue of song.cues||[])addAnchor(anchors,cue.atSeconds,cue.position,song.timeSignature);return anchors.sort((a,b)=>a.seconds-b.seconds)}
function addAnchor(anchors,seconds,position,meter){if(!position||!Number.isFinite(seconds))return;const perMeasure=Math.max(1,Number(meter&&meter.numerator)||4),measure=Number(position.measure),beat=Number(position.beat),tick=Number(position.tick)||0;if(!Number.isFinite(measure)||!Number.isFinite(beat))return;anchors.push({seconds,gridBeat:(measure-1)*perMeasure+(beat-1)+tick/960})}
function gridBeatLabel(gridBeat,perMeasure){const whole=Math.max(0,Math.round(gridBeat)),measure=Math.floor(whole/perMeasure)+1,beat=whole%perMeasure+1;return measure+'.'+beat}
function positionLabel(position,fallback){return position&&Number.isFinite(position.measure)&&Number.isFinite(position.beat)?position.measure+'.'+position.beat:fallback||''}
function format(value){const minutes=Math.floor(value/60),seconds=value-minutes*60;return minutes+':'+seconds.toFixed(3).padStart(6,'0')}
function escapeHtml(value){const node=document.createElement('div');node.textContent=String(value);return node.innerHTML}
window.addEventListener('resize',drawWaveform);
fetch('/api/state',{headers}).then(response=>{if(!response.ok)throw Error('Unauthorized remote link');return response.json()}).then(render).catch(error=>{$('hint').textContent=error.message;$('hint').classList.add('error')});
const events=new EventSource('/api/events?token='+encodeURIComponent(token));events.addEventListener('state',event=>render(JSON.parse(event.data)));events.onopen=()=>{$('status').textContent='CONNECTED';$('status').classList.remove('off')};events.onerror=()=>{$('status').textContent='OFFLINE';$('status').classList.add('off')};
</script>
</body>
</html>`;
