import { createHash, randomUUID } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { confirmSet, type SongPreparationInput } from "../confirmed-set/prepare.js";
import { DEFAULT_SHOW_STATE, type ConfirmedSetManifest, type ConfirmedSetShowState } from "../confirmed-set/manifest.js";

export interface PreparedLibraryChoice { readonly id:string;readonly songId:string;readonly title:string;readonly artist:string;readonly arrangement:string;readonly key:string;readonly bpm:number;readonly manifestPath:string;readonly songIndex:number; }
export interface OperatorSetlistItem extends PreparedLibraryChoice { readonly itemId:string; }
export interface OperatorSetlist { readonly schemaVersion:1;readonly id:string;readonly name:string;readonly items:readonly OperatorSetlistItem[];readonly updatedAt:string; }

export function createOperatorSetlist(name="Sunday Set"):OperatorSetlist{return{schemaVersion:1,id:`set-${randomUUID()}`,name,items:[],updatedAt:new Date().toISOString()};}
export function addPreparedSong(setlist:OperatorSetlist,choice:PreparedLibraryChoice,index=setlist.items.length):OperatorSetlist{if(index<0||index>setlist.items.length)throw new Error("Setlist insertion index is outside the list");const item={...choice,itemId:randomUUID()},items=[...setlist.items];items.splice(index,0,item);return touch(setlist,items);}
export function movePreparedSong(setlist:OperatorSetlist,itemId:string,direction:-1|1):OperatorSetlist{const from=setlist.items.findIndex(item=>item.itemId===itemId),to=from+direction;if(from<0)throw new Error("Setlist item was not found");if(to<0||to>=setlist.items.length)return setlist;const items=[...setlist.items],[item]=items.splice(from,1);items.splice(to,0,item!);return touch(setlist,items);}
export function removePreparedSong(setlist:OperatorSetlist,itemId:string):OperatorSetlist{const items=setlist.items.filter(item=>item.itemId!==itemId);if(items.length===setlist.items.length)throw new Error("Setlist item was not found");return touch(setlist,items);}
export function replacePreparedSong(setlist:OperatorSetlist,itemId:string,choice:PreparedLibraryChoice):OperatorSetlist{const index=setlist.items.findIndex(item=>item.itemId===itemId);if(index<0)throw new Error("Setlist item was not found");const items=[...setlist.items];items[index]={...choice,itemId};return touch(setlist,items);}
export function renameOperatorSetlist(setlist:OperatorSetlist,name:string):OperatorSetlist{if(!name.trim())throw new Error("Setlist name is required");return{...setlist,name:name.trim(),updatedAt:new Date().toISOString()};}

export async function discoverPreparedLibrary(manifestPaths:readonly string[]):Promise<PreparedLibraryChoice[]>{const result:PreparedLibraryChoice[]=[];for(const manifestPath of [...new Set(manifestPaths.map(path=>resolve(path)))]){try{const manifest=JSON.parse(await readFile(manifestPath,"utf8")) as ConfirmedSetManifest;for(const[songIndex,song]of manifest.songs.entries())result.push({id:`${manifestPath}:${songIndex}`,songId:String(song.song.id),title:song.song.title,artist:song.song.artist,arrangement:song.arrangement?.name??"Original Song",key:song.selectedKey,bpm:song.selectedBpm,manifestPath,songIndex});}catch{}}return result.sort((a,b)=>a.title.localeCompare(b.title)||a.arrangement.localeCompare(b.arrangement));}
export async function loadOperatorSetlist(path:string):Promise<OperatorSetlist>{try{const parsed=JSON.parse(await readFile(path,"utf8")) as OperatorSetlist;if(parsed.schemaVersion!==1||!Array.isArray(parsed.items))throw new Error("Unsupported setlist");return parsed;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;return createOperatorSetlist();}}
export async function saveOperatorSetlist(path:string,setlist:OperatorSetlist):Promise<void>{await mkdir(dirname(path),{recursive:true});const temporary=`${path}.${process.pid}.tmp`;await writeFile(temporary,`${JSON.stringify(setlist,null,2)}\n`,"utf8");await rename(temporary,path);}

export async function confirmOperatorSet(input:{readonly setlist:OperatorSetlist;readonly cacheRoot:string;readonly show?:ConfirmedSetShowState;readonly ffmpegPath?:string}){if(!input.setlist.items.length)throw new Error("Add at least one prepared song before Confirm Set");const songs:SongPreparationInput[]=[];for(const item of input.setlist.items){const manifest=JSON.parse(await readFile(item.manifestPath,"utf8")) as ConfirmedSetManifest,song=manifest.songs[item.songIndex];if(!song||String(song.song.id)!==item.songId)throw new Error(`${item.title} no longer matches its prepared source`);const stems=[];for(const stem of song.stems)stems.push({relativePath:basename(stem.sourcePath),role:stem.role,durationSeconds:stem.durationSeconds,sha256:await sha256(stem.sourcePath)});if(!song.liveAssets)throw new Error(`${item.title} has no prepared live assets`);songs.push({preparedSong:song,sourceFolder:dirname(song.stems[0]!.sourcePath),stems,liveAssets:{click:{regularPath:song.liveAssets.click.regularPath,accentPath:song.liveAssets.click.accentPath,events:song.liveAssets.click.events},cues:song.liveAssets.cues.map(cue=>({atSeconds:cue.atSeconds,label:cue.label,sourcePath:cue.audioPath,targetRegionId:cue.targetRegionId})),repeatCuePath:song.liveAssets.repeatCuePath,pad:{key:song.liveAssets.pad.key,sourcePath:song.liveAssets.pad.audioPath}}});}
  const setId=`confirmed-${slug(input.setlist.name)}-${Date.now()}`,ffmpegPath=input.ffmpegPath??process.env.PLAYBACK_FFMPEG_PATH;return confirmSet({setId,setName:input.setlist.name,cacheRoot:input.cacheRoot,songs,show:input.show??DEFAULT_SHOW_STATE,...(ffmpegPath?{ffmpegPath}:{})});
}
function touch(setlist:OperatorSetlist,items:readonly OperatorSetlistItem[]):OperatorSetlist{return{...setlist,items,updatedAt:new Date().toISOString()};}
function slug(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"set";}
async function sha256(path:string){const hash=createHash("sha256");for await(const chunk of createReadStream(path))hash.update(chunk as Buffer);return hash.digest("hex");}
