import { createHash, randomUUID } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { confirmSet, type SongPreparationInput } from "../confirmed-set/prepare.js";
import { DEFAULT_SHOW_STATE, type ConfirmedSetManifest, type ConfirmedSetShowState } from "../confirmed-set/manifest.js";
import { songId, type PreparedSong, type StemMixSetting } from "../domain/song.js";
import { DEFAULT_SONG_TRANSITION, transitionDuration, type SongTransitionSettings, type SongTransitionType } from "../live/song-transition.js";
import { buildWaveformSummary } from "./wav-waveform.js";

export interface PreparedLibraryChoice { readonly id:string;readonly songId:string;readonly title:string;readonly artist:string;readonly arrangement:string;readonly key:string;readonly bpm:number;readonly manifestPath:string;readonly songIndex:number; }
export interface OperatorPreparedSetlistItem extends PreparedLibraryChoice { readonly itemId:string;readonly transitionToNext?:{readonly type:SongTransitionType;readonly continuePad:boolean};readonly stemMix?:readonly StemMixSetting[]; }
export interface OperatorMediaSetlistItem { readonly kind:"media";readonly itemId:string;readonly songId:string;readonly title:string;readonly artist:string;readonly arrangement:string;readonly key:string;readonly bpm:number;readonly sourcePath:string;readonly transitionToNext?:{readonly type:SongTransitionType;readonly continuePad:boolean}; }
export type OperatorSetlistItem = OperatorPreparedSetlistItem | OperatorMediaSetlistItem;
export interface OperatorSetlist { readonly schemaVersion:1;readonly id:string;readonly name:string;readonly items:readonly OperatorSetlistItem[];readonly updatedAt:string; }

export function isMediaSetlistItem(item:OperatorSetlistItem):item is OperatorMediaSetlistItem{return (item as {kind?:string}).kind==="media";}
export function createOperatorSetlist(name="Sunday Set"):OperatorSetlist{return{schemaVersion:1,id:`set-${randomUUID()}`,name,items:[],updatedAt:new Date().toISOString()};}
export function addPreparedSong(setlist:OperatorSetlist,choice:PreparedLibraryChoice,index=setlist.items.length):OperatorSetlist{if(index<0||index>setlist.items.length)throw new Error("Setlist insertion index is outside the list");const item={...choice,itemId:randomUUID(),transitionToNext:{...DEFAULT_SONG_TRANSITION}},items=[...setlist.items];items.splice(index,0,item);return touch(setlist,items);}
export function addMediaFile(setlist:OperatorSetlist,sourcePath:string,index=setlist.items.length):OperatorSetlist{if(index<0||index>setlist.items.length)throw new Error("Setlist insertion index is outside the list");if(!sourcePath.toLowerCase().endsWith(".wav"))throw new Error("Media setlist items must be WAV files");const title=basename(sourcePath).replace(/\.[^.]+$/,"")||"Audio Media",item:OperatorMediaSetlistItem={kind:"media",itemId:randomUUID(),songId:`media-${randomUUID()}`,title,artist:"Audio File",arrangement:"Media File",key:"MEDIA",bpm:120,sourcePath:resolve(sourcePath),transitionToNext:{...DEFAULT_SONG_TRANSITION}},items=[...setlist.items];items.splice(index,0,item);return touch(setlist,items);}
export function movePreparedSong(setlist:OperatorSetlist,itemId:string,direction:-1|1):OperatorSetlist{const from=setlist.items.findIndex(item=>item.itemId===itemId),to=from+direction;if(from<0)throw new Error("Setlist item was not found");if(to<0||to>=setlist.items.length)return setlist;const items=[...setlist.items],[item]=items.splice(from,1);items.splice(to,0,item!);return touch(setlist,items);}
export function reorderPreparedSong(setlist:OperatorSetlist,itemId:string,beforeItemId:string|null):OperatorSetlist{const from=setlist.items.findIndex(item=>item.itemId===itemId);if(from<0)throw new Error("Setlist item was not found");if(beforeItemId===itemId)return setlist;const items=[...setlist.items],[item]=items.splice(from,1);const destination=beforeItemId===null?items.length:items.findIndex(candidate=>candidate.itemId===beforeItemId);if(destination<0)throw new Error("Setlist destination was not found");items.splice(destination,0,item!);return touch(setlist,items);}
export function removePreparedSong(setlist:OperatorSetlist,itemId:string):OperatorSetlist{const items=setlist.items.filter(item=>item.itemId!==itemId);if(items.length===setlist.items.length)throw new Error("Setlist item was not found");return touch(setlist,items);}
export function replacePreparedSong(setlist:OperatorSetlist,itemId:string,choice:PreparedLibraryChoice):OperatorSetlist{const index=setlist.items.findIndex(item=>item.itemId===itemId);if(index<0)throw new Error("Setlist item was not found");const items=[...setlist.items],transitionToNext=items[index]!.transitionToNext;items[index]={...choice,itemId,...(transitionToNext?{transitionToNext}:{})};return touch(setlist,items);}
export function renameOperatorSetlist(setlist:OperatorSetlist,name:string):OperatorSetlist{if(!name.trim())throw new Error("Setlist name is required");return{...setlist,name:name.trim(),updatedAt:new Date().toISOString()};}
export function setOperatorSetTransition(setlist:OperatorSetlist,itemId:string,type:SongTransitionType,continuePad=true):OperatorSetlist{const index=setlist.items.findIndex(item=>item.itemId===itemId);if(index<0)throw new Error("Setlist item was not found");if(index>=setlist.items.length-1)throw new Error("The final song does not have a following transition");const items=[...setlist.items];items[index]={...items[index]!,transitionToNext:{type,continuePad}};return touch(setlist,items);}

export async function discoverPreparedLibrary(manifestPaths:readonly string[]):Promise<PreparedLibraryChoice[]>{const result:PreparedLibraryChoice[]=[];for(const manifestPath of [...new Set(manifestPaths.map(path=>resolve(path)))]){try{const manifest=JSON.parse(await readFile(manifestPath,"utf8")) as ConfirmedSetManifest;for(const[songIndex,song]of manifest.songs.entries()){const arrangement=song.arrangement?.name??"Original Song";if(arrangement!=="Original Song"&&!song.regions.length)continue;result.push({id:`${manifestPath}:${songIndex}`,songId:String(song.song.id),title:song.song.title,artist:song.song.artist,arrangement,key:song.selectedKey,bpm:song.selectedBpm,manifestPath,songIndex});}}catch{}}return result.sort((a,b)=>a.title.localeCompare(b.title)||arrangementSortRank(a)-arrangementSortRank(b)||a.arrangement.localeCompare(b.arrangement));}
export async function loadOperatorSetlist(path:string):Promise<OperatorSetlist>{try{const parsed=JSON.parse(await readFile(path,"utf8")) as OperatorSetlist;if(parsed.schemaVersion!==1||!Array.isArray(parsed.items))throw new Error("Unsupported setlist");return parsed;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;return createOperatorSetlist();}}
export async function saveOperatorSetlist(path:string,setlist:OperatorSetlist):Promise<void>{await mkdir(dirname(path),{recursive:true});const temporary=`${path}.${process.pid}.tmp`;await writeFile(temporary,`${JSON.stringify(setlist,null,2)}\n`,"utf8");await rename(temporary,path);}

export async function confirmOperatorSet(input:{readonly setlist:OperatorSetlist;readonly cacheRoot:string;readonly show?:ConfirmedSetShowState;readonly ffmpegPath?:string;readonly transitionSettings?:SongTransitionSettings;readonly clickRegularPath?:string;readonly clickAccentPath?:string;readonly onProgress?:(status:{progress:number;label:string})=>void}){if(!input.setlist.items.length)throw new Error("Add at least one prepared song before Confirm Set");const songs:SongPreparationInput[]=[];input.onProgress?.({progress:2,label:"Checking prepared song sources"});for(const[index,item]of input.setlist.items.entries()){input.onProgress?.({progress:Math.round(4+(index/input.setlist.items.length)*20),label:`Checking ${item.title}`});if(isMediaSetlistItem(item)){const media=await prepareMediaItem(item);songs.push(media);continue;}const manifest=JSON.parse(await readFile(item.manifestPath,"utf8")) as ConfirmedSetManifest,sourceSong=manifest.songs[item.songIndex],review=(manifest as any).review;if(!sourceSong||String(sourceSong.song.id)!==item.songId)throw new Error(`${item.title} no longer matches its prepared source`);const song:PreparedSong=item.stemMix?{...sourceSong,stemMix:item.stemMix}:sourceSong;if(review&&review.performanceEligible!==true){const issues=autoApprovalIssues(song);if(issues.length)throw new Error(`${item.title} is Analyzer review metadata and cannot be auto-approved: ${issues.join("; ")}`);input.onProgress?.({progress:Math.round(4+(index/input.setlist.items.length)*20),label:`Auto-approving ${item.title}`});}const stems=[];for(const stem of song.stems)stems.push({relativePath:basename(stem.sourcePath),sourcePath:stem.sourcePath,role:stem.role,durationSeconds:stem.durationSeconds,sha256:await sha256(stem.sourcePath)});if (!song.stems.length) throw new Error(`${item.title}: missing playable stems`);
        if (!song.liveAssets) { songs.push({ preparedSong: song, sourceFolder: dirname(song.stems[0]!.sourcePath), stems }); continue; }
songs.push({preparedSong:song,sourceFolder:dirname(song.stems[0]!.sourcePath),stems,liveAssets:{click:{regularPath:input.clickRegularPath??song.liveAssets.click.regularPath,accentPath:input.clickAccentPath??song.liveAssets.click.accentPath,events:song.liveAssets.click.events,templateId:song.liveAssets.click.templateId},cues:song.liveAssets.cues.map(cue=>({...("position" in cue&&cue.position?{position:cue.position}:{}),atSeconds:cue.atSeconds,label:cue.label,sourcePath:cue.audioPath,targetRegionId:cue.targetRegionId})),repeatCuePath:song.liveAssets.repeatCuePath,pad:{key:song.liveAssets.pad.key,sourcePath:song.liveAssets.pad.audioPath}}});}
  const transitions=input.setlist.items.slice(0,-1).map((item,index)=>{const type=item.transitionToNext?.type??DEFAULT_SONG_TRANSITION.type,outgoing=songs[index]!.preparedSong,incoming=songs[index+1]!.preparedSong,last=outgoing.regions.at(-1),first=incoming.regions[0],durationSeconds=transitionDuration(type,last?last.endSeconds-last.startSeconds:5,first?first.endSeconds-first.startSeconds:5,input.transitionSettings);return{fromSongIndex:index,toSongIndex:index+1,type,durationSeconds,continuePad:item.transitionToNext?.continuePad??DEFAULT_SONG_TRANSITION.continuePad};});
  const setId=`confirmed-${slug(input.setlist.name)}-${Date.now()}`,ffmpegPath=input.ffmpegPath??process.env.PLAYBACK_FFMPEG_PATH;return confirmSet({setId,setName:input.setlist.name,cacheRoot:input.cacheRoot,songs,transitions,show:input.show??DEFAULT_SHOW_STATE,onProgress:status=>input.onProgress?.({progress:25+Math.round(status.progress*.75),label:status.label}),...(ffmpegPath?{ffmpegPath}:{})});
}
function touch(setlist:OperatorSetlist,items:readonly OperatorSetlistItem[]):OperatorSetlist{return{...setlist,items,updatedAt:new Date().toISOString()};}
function arrangementSortRank(choice:PreparedLibraryChoice):number{return choice.arrangement==="Original Song"?0:1;}
function slug(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"set";}
async function sha256(path:string){const hash=createHash("sha256");for await(const chunk of createReadStream(path))hash.update(chunk as Buffer);return hash.digest("hex");}
async function prepareMediaItem(item:OperatorMediaSetlistItem):Promise<SongPreparationInput>{const summary=await buildWaveformSummary(item.sourcePath,2400),hash=await sha256(item.sourcePath),stem={relativePath:basename(item.sourcePath),sourcePath:item.sourcePath,role:"media",durationSeconds:summary.durationSeconds,sha256:hash,displayName:item.title},preparedSong:PreparedSong={mediaOnly:true,song:{id:songId(item.songId),title:item.title,artist:item.artist,vendor:"Media",originalKey:item.key,originalBpm:item.bpm,originalTimeSignature:{numerator:4,denominator:4}},selectedKey:item.key,selectedBpm:item.bpm,timeSignature:{numerator:4,denominator:4},durationSeconds:summary.durationSeconds,stems:[{role:"media",sourcePath:item.sourcePath,durationSeconds:summary.durationSeconds,displayName:item.title}],regions:[],cues:[],cacheFingerprint:`media:${hash}`};return{preparedSong,sourceFolder:dirname(item.sourcePath),stems:[stem]};}

function autoApprovalIssues(song:PreparedSong):string[] {
    return !song.stems.length ? ["missing playable stems"] : song.stems.some(stem => !stem.sourcePath) ? ["stem path missing"] : [];
}
