import { app, BrowserWindow, dialog, ipcMain } from "electron";
import { execFile } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { isAbsolute, join, relative, resolve } from "node:path";
import { NativeEngineClient, type NativeAudioDeviceSelection, type NativeAudioRouting, type NativeMidiInputEvent, type NativeMixerMeters, type NativeReadyState, type NativeTransportState } from "../live/native-engine-client.js";
import { MapEditorHistory, type MapCommand } from "../edit/map-editor.js";
import { currentSongMapPath, loadSongMap, mapExists, saveSongMap } from "../edit/map-persistence.js";
import { normalizeRegions, type OriginalSongMap } from "../edit/song-map.js";
import { DEFAULT_ROUTES, PerformanceSession, type LiveBus, type PerformanceEffects } from "../live/performance-session.js";
import { evaluatePerformanceReadiness } from "../live/performance-readiness.js";
import type { ConfirmedSetManifest } from "../confirmed-set/manifest.js";
import { importReaperProject } from "../reaper/rpp-import.js";
import { saveArrangementVersion } from "../reaper/arrangement-persistence.js";
import { prepareArrangementCache } from "../reaper/arrangement-cache.js";
import type { ArrangementImportPreview } from "../reaper/arrangement.js";
import { ArrangementEditorHistory,createArrangementDraft,validateArrangementDraft,type ArrangementCommand } from "../edit/arrangement-editor.js";
import { saveAppArrangement } from "../edit/app-arrangement-save.js";
import { arrangementDraftPath,loadArrangementDraft,saveArrangementDraft } from "../edit/arrangement-draft-persistence.js";
import { editorStemDisplayLabels,loadOrBuildEditorWaveforms,projectEditorWaveforms } from "../edit/editor-workspace.js";
import { evaluateEditorReadiness } from "../edit/editor-readiness.js";
import { arrangementFingerprint,type AppArrangementDraft } from "../edit/arrangement-editor.js";
import { productionDefaults } from "../config/settings.js";
import { importMasterCatalog } from "../library/master-spreadsheet.js";
import { scanMasterLibrary } from "../library/library-scanner.js";
import { addPreparedSong, confirmOperatorSet, discoverPreparedLibrary, loadOperatorSetlist, movePreparedSong, removePreparedSong, renameOperatorSetlist, replacePreparedSong, saveOperatorSetlist, type OperatorSetlist } from "../prep/operator-workflow.js";
import { randomBytes } from "node:crypto";
import { PlaybackCommandBus, type PlaybackCommand } from "../control/command-bus.js";
import { RemoteControlServer, type RemoteControlAddress } from "../control/remote-server.js";
import { networkInterfaces } from "node:os";
import { FOOT_CONTROLLER_PROFILES, MidiInputRouter, type FootControllerProfileId } from "../control/midi-input.js";
import { encodeGldIntent, Gld112SafeClient, type GldIntent } from "../control/mixers/gld112.js";

const projectRoot = resolve(import.meta.dirname, "../../..");
const originalManifestPath=join(projectRoot,".playback-cache","milestone-1-cornerstone-performance-v3","confirmed-set.json"),arrangementManifestPath=join(projectRoot,".playback-cache","arrangements","reaper-72091bdc9061","performance","confirmed-set.json");
const manifestArgument=process.argv.find((value)=>value.startsWith("--manifest="))?.slice("--manifest=".length);
const explicitManifestPath=manifestArgument ? resolve(manifestArgument) : process.env.PLAYBACK_MANIFEST_PATH ? resolve(process.env.PLAYBACK_MANIFEST_PATH) : null;
let manifestPath = explicitManifestPath ?? originalManifestPath;
const enginePath = join(projectRoot, "native", "build", "PlaybackEngineProbe_artefacts", "Release", "PlaybackEngineProbe.exe");
let engine = new NativeEngineClient();
let window: BrowserWindow | null = null;
let statusTimer: NodeJS.Timeout | null = null;
let editor: MapEditorHistory | null = null;
let performance: PerformanceSession | null = null;
let pendingImport:ArrangementImportPreview|null=null;
let selectedMidiOutput:string|null=null;
let selectedAudioDevice:NativeAudioDeviceSelection|null=null;
let selectedAudioRouting:NativeAudioRouting|null=null;
let selectedMidiInput:string|null=null;
let arrangementEditor:ArrangementEditorHistory|null=null;
let controlBus:PlaybackCommandBus|null=null;
let remoteServer:RemoteControlServer|null=null;
let remoteAddress:RemoteControlAddress|null=null;
let lastControlPublish=0;
let midiInputRouter:MidiInputRouter|null=null;
let libraryActivity:{sync:"idle"|"running"|"complete"|"fault";analyzer:"idle"|"scanning"|"waiting";startedAt:string|null;finishedAt:string|null;message:string;lastScan:any|null}={sync:"idle",analyzer:"idle",startedAt:null,finishedAt:null,message:"Library has not been scanned in this session.",lastScan:null};

async function armNativeSong(songIndex:number):Promise<NativeReadyState>{
  if(statusTimer){clearInterval(statusTimer);statusTimer=null;}
  await engine.closeAndWait();engine=new NativeEngineClient();
  engine.on("transport",(state:NativeTransportState)=>{performance?.updatePosition(state.positionSeconds);sendToRenderer("playback:transport",state);sendToRenderer("performance:state",performance?.snapshot);const now=Date.now();if(now-lastControlPublish>=100){lastControlPublish=now;controlBus?.publishState();}});
  engine.on("fault",(error:Error)=>{performance?.reportFault(error.message);sendToRenderer("performance:state",performance?.snapshot);controlBus?.publishState();});
  engine.on("midi-input",(event:NativeMidiInputEvent)=>{void midiInputRouter?.handle(event);sendToRenderer("control:midi-input",event);});
  engine.on("meters",(meters:NativeMixerMeters)=>sendToRenderer("mixer:meters",meters));
  const ready=await engine.start(enginePath,manifestPath,songIndex,selectedMidiOutput,selectedAudioDevice,selectedMidiInput,selectedAudioRouting??undefined);
  statusTimer=setInterval(()=>engine.requestStatus(),33);return ready;
}

async function createWindow(): Promise<void> {
  window = new BrowserWindow({
    width: 1920, height: 1080, minWidth: 1000, minHeight: 650, show:false,
    backgroundColor: "#0a0d12", title: "Playback V3",
    webPreferences: { preload: join(projectRoot, "desktop-preload.cjs"), contextIsolation: true, nodeIntegration: false },
  });
  try{const settings=JSON.parse(await readFile(join(projectRoot,".playback-data","device-settings.json"),"utf8"));selectedMidiOutput=typeof settings.midiOutputName==="string"?settings.midiOutputName:null;selectedMidiInput=typeof settings.midiInputName==="string"?settings.midiInputName:null;selectedAudioDevice=settings.audioDevice&&typeof settings.audioDevice.type==="string"&&typeof settings.audioDevice.name==="string"?settings.audioDevice:null;selectedAudioRouting=settings.audioRouting??null;}catch{}
  if(selectedAudioDevice){const savedDevice=selectedAudioDevice,devices=await listAudioDevices();if(!devices.some(device=>sameAudioDevice(device,savedDevice))){console.warn(`Saved audio device is unavailable; using the system default: ${savedDevice.type} / ${savedDevice.name}`);selectedAudioDevice=null;await saveDeviceSettings();}}
  if(!explicitManifestPath){try{const active=JSON.parse(await readFile(join(projectRoot,".playback-data","active-arrangement.json"),"utf8")),candidate=resolve(String(active.manifestPath??""));if(isPreparedManifestPath(candidate)){await readFile(candidate,"utf8");manifestPath=candidate;}}catch{}}
  const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as ConfirmedSetManifest;
  const selectedSongPath=join(projectRoot,".playback-data","selected-song.json");
  let selectedSongIndex=0;
  try{const selected=JSON.parse(await readFile(selectedSongPath,"utf8"));if(Number.isInteger(selected.index)&&manifest.songs[selected.index])selectedSongIndex=selected.index;}catch{}
  if(selectedAudioRouting&&!Array.isArray((selectedAudioRouting as any).stemChannels))selectedAudioRouting={...selectedAudioRouting,stemChannels:selectedAudioRouting.stems.map(()=>2 as const)};
  if(!selectedAudioRouting)selectedAudioRouting=defaultAudioRouting(manifest.songs[selectedSongIndex]!.stems.length);
  validateAudioRouting(selectedAudioRouting,manifest.songs[selectedSongIndex]!.stems.length);
  const operatorSetlistPath=join(projectRoot,".playback-data","draft-setlist.json");
  let operatorSetlist:OperatorSetlist=await loadOperatorSetlist(operatorSetlistPath);
  let currentReady:NativeReadyState|null=null,nativeArmError:string|null=null;
  try{currentReady=await armNativeSong(selectedSongIndex);}catch(error){nativeArmError=error instanceof Error?error.message:String(error);}
  const ready=currentReady??{deviceOpenMs:0,armMs:0,stems:0,nextReady:false,nextIndex:-1,outputChannels:0,routingReady:false,stereoFallback:false,midiEvents:0,midiEnabled:false};
  const preparedSong=(manifest as any).songs[selectedSongIndex];
  const editableMap:OriginalSongMap={schemaVersion:1,songId:preparedSong.song.id,bpm:preparedSong.selectedBpm,timeSignature:preparedSong.timeSignature,durationSeconds:preparedSong.durationSeconds,reviewState:"draft",revision:0,source:{kind:"analyzer",path:"analysis/regions.json",importedAt:new Date().toISOString()},regions:normalizeRegions(preparedSong.regions),cues:preparedSong.liveAssets.cues.map((cue:any,index:number)=>({id:`cue-${String(index+1).padStart(4,"0")}`,phrase:cue.label,atSeconds:cue.atSeconds,targetRegionId:cue.targetRegionId,enabled:true,audioPath:cue.audioPath,sourceLabel:cue.label}))};
  const mapRoot=join(projectRoot,".playback-data"),savedMapPath=currentSongMapPath(mapRoot,editableMap.songId);
  const initialMap=await mapExists(savedMapPath)?await loadSongMap(savedMapPath):editableMap;
  editor=new MapEditorHistory(initialMap);
  const baseArrangementDraft=createArrangementDraft(preparedSong);
  const arrangementSourceId=preparedSong.arrangement?.id??"original-song";
  const draftFile=arrangementDraftPath(mapRoot,preparedSong.song.id,arrangementSourceId);
  const restoredDraft=await loadArrangementDraft(draftFile,preparedSong.song.id);
  arrangementEditor=new ArrangementEditorHistory(restoredDraft??baseArrangementDraft);
  let savedDraft:AppArrangementDraft=restoredDraft??baseArrangementDraft;
  const waveformCachePath=join(projectRoot,".playback-cache","editor-waveforms",`${safeCacheName(preparedSong.cacheFingerprint)}.json`);
  const originalLabelManifest=JSON.parse(await readFile(originalManifestPath,"utf8")) as ConfirmedSetManifest;
  const originalLabelSong=originalLabelManifest.songs.find(item=>item.song.id===preparedSong.song.id);
  const stemDisplayLabels=editorStemDisplayLabels(preparedSong,originalLabelSong);
  const sourceWaveforms=loadOrBuildEditorWaveforms(preparedSong,waveformCachePath,2400,"ffmpeg",stemDisplayLabels);
  const workspaceState=async()=>{const draft=arrangementEditor!.draft,waveforms=projectEditorWaveforms(await sourceWaveforms,draft),padFile=`Pad_${padKey(draft.selectedKey)}.wav`,readiness=await evaluateEditorReadiness({draft,source:preparedSong,cacheRoot:join(projectRoot,".playback-cache"),clickRegularPath:join(productionDefaults.clickFolder,"CLICK.wav"),clickAccentPath:join(productionDefaults.clickFolder,"CLICK ACCENT.wav"),cueDirectory:productionDefaults.cueFolder,padPath:join(productionDefaults.padFolder,padFile),routingReady:currentReady?.routingReady===true,midiOutputName:selectedMidiOutput});return{draft,waveforms,readiness,dirty:arrangementFingerprint(draft)!==arrangementFingerprint(savedDraft),canUndo:arrangementEditor!.canUndo,canRedo:arrangementEditor!.canRedo,source:{kind:preparedSong.arrangement?.sourceType??"original-song",id:arrangementSourceId,name:preparedSong.arrangement?.name??"Original Song",hash:preparedSong.arrangement?.sourceSha256??preparedSong.cacheFingerprint},originalFacts:preparedSong.song};};
  const readinessFor=(songIndex:number,native:NativeReadyState|null=currentReady,error:string|null=nativeArmError)=>evaluatePerformanceReadiness({manifest,manifestPath,songIndex,native,midiOutputName:selectedMidiOutput,nativeError:error});
  const effects:PerformanceEffects={play:()=>engine.play(),pause:()=>engine.pause(),stop:()=>engine.stop(),seek:(seconds)=>engine.seek(seconds),panic:()=>engine.panic(),announceRecovery:(regionId,atSeconds,repeatAtSeconds)=>engine.announceRecovery(regionId,atSeconds,repeatAtSeconds),cancelTransition:()=>engine.cancelTransition(),recover:()=>engine.recover(),setBus:(bus:LiveBus,enabled:boolean)=>{if(bus==="music")enabled?engine.musicOn():engine.musicOff();else if(bus==="click")enabled?engine.clickOn():engine.clickOff();else if(bus==="cue")enabled?engine.cueOn():engine.cueOff();else enabled?engine.padOn():engine.padOff();},setBusGain:(bus,gain)=>engine.setBusGain(bus,gain),setMixerChannel:channel=>engine.setMixerChannel(channel.index,channel.gain,channel.muted,channel.solo,channel.iem),setMasterGain:gain=>engine.setMasterGain(gain),selectSong:async(index)=>{const selected=await engine.selectSong(index);currentReady=selected;nativeArmError=null;return readinessFor(index,selected,null);}};
  const initialReadiness=await readinessFor(selectedSongIndex);
  performance=new PerformanceSession(manifest,effects,manifest.show?.routing??DEFAULT_ROUTES,initialReadiness,manifest.show?.mixer,selectedSongIndex);
  controlBus=new PlaybackCommandBus(performance,manifest.name);
  controlBus.onState(state=>sendToRenderer("control:state",state));
  const controlSettings=await loadOrCreateControlSettings();
  midiInputRouter=new MidiInputRouter(controlBus,FOOT_CONTROLLER_PROFILES[controlSettings.footControllerProfile]);
  remoteServer=new RemoteControlServer(controlBus,{token:controlSettings.token,host:controlSettings.lanEnabled?"0.0.0.0":"127.0.0.1",httpPort:controlSettings.httpPort,oscPort:controlSettings.oscPort,enableOsc:controlSettings.oscEnabled,oscTokenRequired:controlSettings.lanEnabled});
  try{remoteAddress=await remoteServer.start();}catch(error){console.error("Remote control adapter unavailable",error);remoteAddress=null;}
  if(manifest.show)for(const[bus,gain]of Object.entries(manifest.show.mixer))engine.setBusGain(bus as LiveBus,gain);
  if(nativeArmError)performance.reportFault(nativeArmError);
  ipcMain.handle("playback:bootstrap",async()=>{const activeSongIndex=performance!.snapshot.songIndex,activeSong=manifest.songs[activeSongIndex]!,activeWaveform=JSON.parse(await readFile(activeSong.waveformPath!,"utf8")),labels=editorStemDisplayLabels(activeSong,originalLabelManifest.songs.find(item=>item.song.id===activeSong.song.id));return{ready:currentReady??ready,manifest,waveform:activeWaveform,stemLabels:labels,activeSongIndex,performance:performance!.snapshot,selectedManifestPath:manifestPath,arrangements:await listPreparedArrangements(manifest),midi:{outputs:await listMidiOutputs(),selectedOutput:selectedMidiOutput,enabled:selectedMidiOutput!==null},audio:{devices:await listAudioDevices(),selectedDevice:selectedAudioDevice,routing:selectedAudioRouting,routingLabels:labels,routingReady:(currentReady??ready).routingReady===true,iemReady:(currentReady??ready).iemReady===true,outputChannels:(currentReady??ready).outputChannels??0,stereoFallback:(currentReady??ready).stereoFallback===true}};});
  const preparedChoices=async()=>discoverPreparedLibrary(await allPreparedManifestPaths());
  ipcMain.handle("prep:get",async()=>({setlist:operatorSetlist,prepared:await preparedChoices()}));
  ipcMain.handle("prep:status",async()=>({...libraryActivity,libraryRoot:productionDefaults.libraryRoot,masterWorkbookPath:productionDefaults.masterWorkbookPath}));
  ipcMain.handle("prep:scan",async()=>{libraryActivity={...libraryActivity,sync:"running",analyzer:"scanning",startedAt:new Date().toISOString(),finishedAt:null,message:"Reading the master workbook and checking analyzer files…"};sendToRenderer("prep:status",libraryActivity);try{const catalog=await importMasterCatalog(productionDefaults.masterWorkbookPath),scan=await scanMasterLibrary(catalog.songs),result={counts:scan.counts,scannedAt:scan.scannedAt,songs:scan.songs.map(record=>({songId:record.master.catalogId,title:record.master.title,artist:record.master.artist,vendor:record.master.vendor,key:record.master.key,bpm:record.master.bpm,readiness:record.readiness,issues:record.issues}))};libraryActivity={...libraryActivity,sync:"complete",analyzer:result.counts["needs-analysis"]>0?"waiting":"idle",finishedAt:new Date().toISOString(),message:result.counts["needs-analysis"]>0?`${result.counts["needs-analysis"]} song(s) are waiting for analyzer output.`:"Library and analyzer metadata are current.",lastScan:result};sendToRenderer("prep:status",libraryActivity);return result;}catch(error){libraryActivity={...libraryActivity,sync:"fault",analyzer:"idle",finishedAt:new Date().toISOString(),message:error instanceof Error?error.message:String(error)};sendToRenderer("prep:status",libraryActivity);throw error;}});
  ipcMain.handle("prep:command",async(_event,command:any)=>{if(command.action==="add"){const choice=(await preparedChoices()).find(item=>item.id===command.choiceId);if(!choice)throw new Error("Prepared song version is no longer available");operatorSetlist=addPreparedSong(operatorSetlist,choice);}else if(command.action==="replace"){const choice=(await preparedChoices()).find(item=>item.id===command.choiceId);if(!choice)throw new Error("Prepared song version is no longer available");operatorSetlist=replacePreparedSong(operatorSetlist,command.itemId,choice);}else if(command.action==="remove")operatorSetlist=removePreparedSong(operatorSetlist,command.itemId);else if(command.action==="move")operatorSetlist=movePreparedSong(operatorSetlist,command.itemId,command.direction);else if(command.action==="rename")operatorSetlist=renameOperatorSetlist(operatorSetlist,command.name);else if(command.action==="clear")operatorSetlist={...operatorSetlist,items:[],updatedAt:new Date().toISOString()};else throw new Error("Unknown setlist command");await saveOperatorSetlist(operatorSetlistPath,operatorSetlist);return{setlist:operatorSetlist,prepared:await preparedChoices()};});
  ipcMain.handle("prep:confirm",async(_event,options?:{selectedIndex?:number})=>{const result=await confirmOperatorSet({setlist:operatorSetlist,cacheRoot:join(projectRoot,".playback-cache","confirmed-sets"),...(manifest.show?{show:manifest.show}:{})});await mkdir(join(projectRoot,".playback-data"),{recursive:true});await writeFile(join(projectRoot,".playback-data","active-arrangement.json"),JSON.stringify({manifestPath:result.manifestPath,selectedAt:new Date().toISOString()},null,2));if(Number.isInteger(options?.selectedIndex)&&result.manifest.songs[options!.selectedIndex!])await writeFile(selectedSongPath,JSON.stringify({index:options!.selectedIndex,selectedAt:new Date().toISOString()},null,2));setTimeout(()=>{app.relaunch({args:process.argv.slice(1).filter(value=>!value.startsWith("--manifest="))});app.exit(0);},500);return{manifestPath:result.manifestPath,songs:result.manifest.songs.length,readiness:result.readiness};});
  ipcMain.handle("midi:set-output",async(_event,name:string|null)=>{const outputs=await listMidiOutputs();if(name!==null&&!outputs.includes(name))throw new Error("MIDI output is no longer available");selectedMidiOutput=name;await saveDeviceSettings();currentReady=await armNativeSong(performance!.snapshot.songIndex);nativeArmError=null;const readiness=await readinessFor(performance!.snapshot.songIndex);performance!.setReadiness(readiness);sendToRenderer("performance:state",performance!.snapshot);return{selectedOutput:name,enabled:name!==null,ready:currentReady,readiness};});
  ipcMain.handle("audio:set-device",async(_event,device:NativeAudioDeviceSelection|null)=>{const devices=await listAudioDevices();if(device&&!devices.some(x=>x.type===device.type&&x.name===device.name))throw new Error("Audio device is no longer available");selectedAudioDevice=device;await saveDeviceSettings();currentReady=await armNativeSong(performance!.snapshot.songIndex);nativeArmError=null;const readiness=await readinessFor(performance!.snapshot.songIndex);performance!.setReadiness(readiness);sendToRenderer("performance:state",performance!.snapshot);return{selectedDevice:device,routingReady:currentReady.routingReady===true,iemReady:currentReady.iemReady===true,outputChannels:currentReady.outputChannels??0,stereoFallback:currentReady.stereoFallback===true,readiness};});
  ipcMain.handle("audio:set-routing",async(_event,routing:NativeAudioRouting)=>{validateAudioRouting(routing,manifest.songs[performance!.snapshot.songIndex]!.stems.length);selectedAudioRouting={stems:[...routing.stems],stemChannels:[...routing.stemChannels],click:routing.click,cue:routing.cue,pad:routing.pad,iem:routing.iem};await saveDeviceSettings();currentReady=await armNativeSong(performance!.snapshot.songIndex);nativeArmError=null;const readiness=await readinessFor(performance!.snapshot.songIndex);performance!.setReadiness(readiness);sendToRenderer("performance:state",performance!.snapshot);return{routing:selectedAudioRouting,routingReady:currentReady.routingReady===true,iemReady:currentReady.iemReady===true,outputChannels:currentReady.outputChannels??0,readiness};});
  ipcMain.handle("audio:refresh",async()=>{const devices=await listAudioDevices();let fellBack=false;if(selectedAudioDevice){const activeDevice=selectedAudioDevice;if(!devices.some(device=>sameAudioDevice(device,activeDevice))){selectedAudioDevice=null;fellBack=true;await saveDeviceSettings();currentReady=await armNativeSong(performance!.snapshot.songIndex);nativeArmError=null;const readiness=await readinessFor(performance!.snapshot.songIndex);performance!.setReadiness(readiness);sendToRenderer("performance:state",performance!.snapshot);}}return{devices,selectedDevice:selectedAudioDevice,fellBack,routingReady:currentReady?.routingReady===true,iemReady:currentReady?.iemReady===true,outputChannels:currentReady?.outputChannels??0,stereoFallback:currentReady?.stereoFallback===true};});
  ipcMain.handle("arrangement:select",async(_event,path:string)=>{const selectedPath=resolve(path);if(!(await listPreparedArrangements(manifest)).some(item=>item.path===selectedPath))throw new Error("Arrangement is not an approved prepared version");await mkdir(join(projectRoot,".playback-data"),{recursive:true});await writeFile(join(projectRoot,".playback-data","active-arrangement.json"),JSON.stringify({manifestPath:selectedPath,selectedAt:new Date().toISOString()},null,2));app.relaunch({args:[...process.argv.slice(1).filter((value)=>!value.startsWith("--manifest=")),`--manifest=${selectedPath}`]});app.exit(0);});
  ipcMain.handle("reaper:preview",async()=>{const chosen=await dialog.showOpenDialog(window!,{title:"Import Reaper Arrangement",properties:["openFile"],filters:[{name:"Reaper projects",extensions:["rpp"]}]});if(chosen.canceled||!chosen.filePaths[0])return null;pendingImport=await importReaperProject(chosen.filePaths[0],preparedSong.song.id,preparedSong);return pendingImport;});
  ipcMain.handle("reaper:commit",async(_event,action:"new"|"replace"|"cancel")=>{if(action==="cancel"){pendingImport=null;return{cancelled:true};}if(!pendingImport)throw new Error("No Reaper import is awaiting confirmation");const arrangement=pendingImport.arrangement,savedPath=await saveArrangementVersion(join(projectRoot,".playback-metadata"),arrangement),prepared=await prepareArrangementCache(arrangement,join(projectRoot,".playback-cache","arrangements"));if(action==="replace"){await mkdir(join(projectRoot,".playback-data"),{recursive:true});await writeFile(join(projectRoot,".playback-data","active-arrangement.json"),JSON.stringify({songId:arrangement.songId,arrangementId:arrangement.id,manifestPath:prepared.manifestPath,selectedAt:new Date().toISOString()},null,2));}pendingImport=null;return{savedPath,preparedManifestPath:prepared.manifestPath,action};});
  ipcMain.handle("performance:get",()=>performance!.snapshot);
  ipcMain.handle("set:select-song",async(_event,index:number)=>{if(!Number.isInteger(index)||!manifest.songs[index])throw new Error("Song is outside the confirmed set");await mkdir(join(projectRoot,".playback-data"),{recursive:true});await writeFile(selectedSongPath,JSON.stringify({index,selectedAt:new Date().toISOString()},null,2));setTimeout(()=>{app.relaunch({args:process.argv.slice(1)});app.exit(0);},150);return{index};});
  ipcMain.handle("performance:command",async(_event,value:any)=>{if(value.action==="clear-fault"){currentReady=await armNativeSong(performance!.snapshot.songIndex);nativeArmError=null;performance!.setReadiness(await readinessFor(performance!.snapshot.songIndex));performance!.clearFault();controlBus!.publishState();return performance!.snapshot;}const result=await controlBus!.dispatch(toPlaybackCommand(value),"ui");if(!result.ok)throw new Error(result.error);return result.state;});
  ipcMain.handle("control:get",async()=>({address:remoteAddress,token:controlSettings.token,lanEnabled:controlSettings.lanEnabled,oscEnabled:controlSettings.oscEnabled,urls:controlUrls(controlSettings,remoteAddress),state:controlBus!.state(),midiInput:{devices:await listMidiInputs(),selected:selectedMidiInput,profile:controlSettings.footControllerProfile,enabled:currentReady?.midiInputEnabled===true},gld:{...controlSettings.gld,devices:await listMidiOutputs(),writesLocked:true}}));
  ipcMain.handle("control:command",async(_event,command:PlaybackCommand)=>{const result=await controlBus!.dispatch(command,"ui");if(!result.ok)throw new Error(result.error);return result;});
  ipcMain.handle("control:set-settings",async(_event,next:{lanEnabled?:boolean;oscEnabled?:boolean})=>{const updated={...controlSettings,lanEnabled:next.lanEnabled??controlSettings.lanEnabled,oscEnabled:next.oscEnabled??controlSettings.oscEnabled,updatedAt:new Date().toISOString()};await writeControlSettings(updated);await remoteServer?.close();setTimeout(()=>{app.relaunch({args:process.argv.slice(1)});app.exit(0);},250);return updated;});
  ipcMain.handle("control:set-midi-input",async(_event,next:{name:string|null;profile:FootControllerProfileId})=>{const devices=await listMidiInputs();if(next.name!==null&&!devices.includes(next.name))throw new Error("MIDI input is no longer available");if(!(next.profile in FOOT_CONTROLLER_PROFILES))throw new Error("Unknown foot controller profile");selectedMidiInput=next.name;controlSettings.footControllerProfile=next.profile;await Promise.all([saveDeviceSettings(),writeControlSettings({...controlSettings,updatedAt:new Date().toISOString()})]);midiInputRouter=new MidiInputRouter(controlBus!,FOOT_CONTROLLER_PROFILES[next.profile]);currentReady=await armNativeSong(performance!.snapshot.songIndex);nativeArmError=null;performance!.setReadiness(await readinessFor(performance!.snapshot.songIndex,currentReady,null));return{selected:selectedMidiInput,profile:next.profile,enabled:currentReady.midiInputEnabled===true};});
  ipcMain.handle("control:gld-preview",(_event,value:{midiChannel:number;intent:GldIntent})=>new Gld112SafeClient({model:"GLD-112",host:"preview-only",port:51325,midiChannel:value.midiChannel}).preview(value.intent));
  ipcMain.handle("control:gld-test",async(_event,value:{midiOutputName:string;midiChannel:number})=>{if(!Number.isInteger(value.midiChannel)||value.midiChannel<1||value.midiChannel>16)throw new Error("GLD MIDI channel must be between 1 and 16");const outputs=await listMidiOutputs();if(!value.midiOutputName||!outputs.includes(value.midiOutputName))throw new Error("GLD MIDI output is not available");await testMidiOutput(value.midiOutputName);controlSettings.gld={...controlSettings.gld,midiOutputName:value.midiOutputName,midiChannel:value.midiChannel};await writeControlSettings({...controlSettings,updatedAt:new Date().toISOString()});return{status:"connection-tested",selected:value.midiOutputName,midiChannel:value.midiChannel,writesLocked:true};});
  ipcMain.handle("control:gld-send",async(_event,intent:GldIntent)=>{if(!controlSettings.gld.writesEnabled)throw new Error("GLD writes are locked until the physical test/learn acceptance is approved");if(!controlSettings.gld.midiOutputName)throw new Error("GLD MIDI output is disabled");const preview=encodeGldIntent(intent,controlSettings.gld.midiChannel);await sendMidiBytes(controlSettings.gld.midiOutputName,preview.bytes);return{...preview,output:controlSettings.gld.midiOutputName,midiChannel:controlSettings.gld.midiChannel};});
  ipcMain.handle("editor:get",()=>editor!.map);
  ipcMain.handle("editor:command",(_event,command:MapCommand)=>editor!.execute(command));
  ipcMain.handle("editor:undo",()=>editor!.undo()); ipcMain.handle("editor:redo",()=>editor!.redo());
  ipcMain.handle("editor:save",async()=>saveSongMap(mapRoot,editor!.map));
  ipcMain.handle("editor:approve",async()=>{const map=editor!.execute({type:"approve-map"});const saved=await saveSongMap(mapRoot,map);return{map,saved};});
  ipcMain.handle("editor:audition-cue",async(_event,cueId:string)=>{const cue=editor!.map.cues.find((item)=>item.id===cueId);if(!cue)throw new Error("Cue not found");const bytes=await readFile(cue.audioPath);return`data:audio/wav;base64,${bytes.toString("base64")}`;});
  ipcMain.handle("arrange:get",()=>arrangementEditor!.draft);
  ipcMain.handle("arrange:workspace",workspaceState);
  ipcMain.handle("arrange:command",(_event,command:ArrangementCommand)=>arrangementEditor!.execute(command));
  ipcMain.handle("arrange:undo",()=>arrangementEditor!.undo());
  ipcMain.handle("arrange:redo",()=>arrangementEditor!.redo());
  ipcMain.handle("arrange:save-draft",async()=>{await saveArrangementDraft(draftFile,arrangementEditor!.draft);savedDraft=arrangementEditor!.draft;return workspaceState();});
  ipcMain.handle("arrange:revert",async()=>{const restored=await loadArrangementDraft(draftFile,preparedSong.song.id);savedDraft=restored??baseArrangementDraft;arrangementEditor!.replace(savedDraft);return workspaceState();});
  ipcMain.handle("arrange:audition-cue",async(_event,cueId:string)=>{const cue=arrangementEditor!.draft.cues.find(item=>item.id===cueId);if(!cue)throw new Error("Cue not found");return cuePreviewData(cue.phrase,preparedSong);});
  ipcMain.handle("arrange:save",async()=>{const issues=validateArrangementDraft(arrangementEditor!.draft);if(issues.length)throw new Error(`Arrangement is not ready: ${issues.join("; ")}`);const result=await saveAppArrangement({draft:arrangementEditor!.draft,source:preparedSong,metadataRoot:join(projectRoot,".playback-metadata"),cacheRoot:join(projectRoot,".playback-cache"),stemDisplayLabels});await saveArrangementDraft(draftFile,arrangementEditor!.draft);savedDraft=arrangementEditor!.draft;return result;});
  ipcMain.on("playback:command", (_event, command: string, value?: number) => {
    if (command === "play") engine.play();
    else if (command === "pause") engine.pause();
    else if (command === "stop") engine.stop();
    else if (command === "seek" && typeof value === "number") engine.seek(value);
    else if (command === "pad_on") engine.padOn();
    else if (command === "pad_off") engine.padOff();
  });
  await window.loadFile(join(projectRoot, "ui-dist", "index.html"));
  window.maximize();window.show();
  if(process.env.PLAYBACK_E2E_CONTROL){await new Promise(resolveDelay=>setTimeout(resolveDelay,500));const result=await window.webContents.executeJavaScript(`(async()=>{document.querySelector('#remoteControl').click();for(let i=0;i<50&&!document.querySelector('#remoteSettings').open;i++)await new Promise(r=>setTimeout(r,50));document.querySelector('#previewGld').click();await new Promise(r=>setTimeout(r,50));const control=await window.playback.control.get(),base=new URL(control.urls[0]).origin,response=await fetch(base+'/api/command',{method:'POST',headers:{Authorization:'Bearer '+control.token,'Content-Type':'application/json'},body:JSON.stringify({type:'transport.stop'})}),command=await response.json();return{dialog:document.querySelector('#remoteSettings').open,status:document.querySelector('#remoteStatus').textContent,urlHasToken:document.querySelector('#remoteUrl').value.includes('token='),address:control.address,lanEnabled:control.lanEnabled,oscEnabled:control.oscEnabled,regions:control.state.songs[0].regions.length,commandOk:command.ok,playing:command.state.playing,midiInputs:document.querySelector('#midiInputDevice').options.length-1,midiProfile:document.querySelector('#footControllerProfile').value,gldWritesLocked:control.gld.writesLocked,gldPreview:document.querySelector('#gldHex').textContent};})()`);console.log(`CONTROL_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_PREP){await new Promise(resolveDelay=>setTimeout(resolveDelay,600));const result=await window.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));document.querySelector('#prepMode').click();for(let i=0;i<100&&!document.querySelectorAll('#preparedLibrary article').length;i++)await wait(100);document.querySelector('#scanLibrary').click();for(let i=0;i<300&&document.querySelector('#scanLibrary').disabled;i++)await wait(100);return{visible:!document.querySelector('#prepWorkspace').hidden,prepared:document.querySelectorAll('#preparedLibrary article').length,catalog:document.querySelectorAll('#catalogRows article').length,summary:document.querySelector('#librarySummary').textContent.trim(),setName:document.querySelector('#setlistName').value,confirmDisabled:document.querySelector('#confirmSet').disabled};})()`);console.log(`PREP_WORKFLOW_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_DRAFT_SAVE){await new Promise(resolveDelay=>setTimeout(resolveDelay,500));const result=await window.webContents.executeJavaScript(`(async()=>{await window.playback.arrange.command({type:'set-name',name:'Persistent Editor Draft Validation'});const saved=await window.playback.arrange.saveDraft();return{name:saved.draft.name,dirty:saved.dirty,revision:saved.draft.revision};})()`);console.log(`EDITOR_DRAFT_SAVE_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_DRAFT_RESTORE){await new Promise(resolveDelay=>setTimeout(resolveDelay,500));const result=await window.webContents.executeJavaScript(`(async()=>{const restored=await window.playback.arrange.workspace();return{name:restored.draft.name,dirty:restored.dirty,revision:restored.draft.revision,source:restored.source.name,readiness:restored.readiness.status};})()`);console.log(`EDITOR_DRAFT_RESTORE_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_EDITOR_SAVE){await new Promise(resolveDelay=>setTimeout(resolveDelay,500));const result=await window.webContents.executeJavaScript(`(async()=>{await window.playback.arrange.command({type:'set-name',name:'Cornerstone Editor Workspace Validation'});const before=await window.playback.arrange.workspace(),saved=await window.playback.arrange.save();return{beforeReadiness:before.readiness.status,name:saved.arrangement.name,id:saved.id,manifestPath:saved.manifestPath,regions:saved.arrangement.regions.length,key:saved.arrangement.selectedKey,bpm:saved.arrangement.selectedBpm};})()`);console.log(`EDITOR_RENDER_SAVE_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_EDITOR_LABELS){await new Promise(resolveDelay=>setTimeout(resolveDelay,500));const result=await window.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));document.querySelector('#editMode').click();for(let i=0;i<100&&document.querySelector('#draftState').textContent==='LOADING';i++)await wait(100);document.querySelector('#stemsView').click();await wait(100);return{source:document.querySelector('#editorSource').textContent,labels:[...document.querySelectorAll('#stemLabelItems label')].map(label=>label.textContent),rows:document.querySelectorAll('.stem-row').length};})()`);console.log(`EDITOR_LABELS_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_EDITOR_RESIZE){await new Promise(resolveDelay=>setTimeout(resolveDelay,500));const result=await window.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));document.querySelector('#editMode').click();for(let i=0;i<100&&document.querySelector('#draftState').textContent==='LOADING';i++)await wait(100);document.querySelector('#stemsView').click();await wait(100);const initialTimeline=document.querySelector('#editorTimeline').getBoundingClientRect(),initialRow=document.querySelector('.stem-row').getBoundingClientRect();document.querySelector('#widthUp').click();document.querySelector('#widthUp').click();document.querySelector('#heightUp').click();await wait(100);const timeline=document.querySelector('#editorTimeline').getBoundingClientRect(),row=document.querySelector('.stem-row').getBoundingClientRect(),label=document.querySelector('#stemLabelItems label').getBoundingClientRect(),canvas=document.querySelector('.stem-row canvas').getBoundingClientRect(),playhead=document.querySelector('#editorPlayhead').getBoundingClientRect(),controls=document.querySelector('#expandedSizeControls'),controlRect=controls.getBoundingClientRect();return{zoom:Number(document.querySelector('#editorZoom').value),initialWidth:initialTimeline.width,width:timeline.width,initialHeight:initialRow.height,height:row.height,labelHeight:label.height,canvasLeft:canvas.left,timelineLeft:timeline.left,playheadLeft:playhead.left,leftDelta:Math.abs(canvas.left-timeline.left),playheadDelta:Math.abs(playhead.left-timeline.left),controlsHidden:controls.hidden,controlsDisplay:getComputedStyle(controls).display,controlsRect:{left:controlRect.left,top:controlRect.top,width:controlRect.width,height:controlRect.height}};})()`);console.log(`EDITOR_RESIZE_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_EDITOR_ALIGNMENT){await new Promise(resolveDelay=>setTimeout(resolveDelay,500));const result=await window.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));document.querySelector('#editMode').click();for(let i=0;i<100&&document.querySelector('#draftState').textContent==='LOADING';i++)await wait(100);document.querySelector('#stemsView').click();await wait(100);const timeline=document.querySelector('#editorTimeline').getBoundingClientRect(),canvas=document.querySelector('.stem-row canvas').getBoundingClientRect(),ruler=document.querySelector('#editorRuler').getBoundingClientRect(),playhead=document.querySelector('#editorPlayhead').getBoundingClientRect(),gutter=document.querySelector('#stemLabelGutter').getBoundingClientRect();return{stems:document.querySelectorAll('.stem-row').length,timelineLeft:timeline.left,canvasLeft:canvas.left,rulerLeft:ruler.left,playheadLeft:playhead.left,gutterRight:gutter.right,leftDelta:Math.abs(timeline.left-canvas.left),widthDelta:Math.abs(timeline.width-canvas.width),playheadDeltaAtZero:Math.abs(timeline.left-playhead.left)};})()`);console.log(`EDITOR_ALIGNMENT_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_MIXER){await new Promise(resolveDelay=>setTimeout(resolveDelay,700));const result=await window.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));const first=document.querySelector('.daw-channel[data-mixer-index="0"]'),mute=first.querySelector('[data-mixer-switch="muted"]'),solo=first.querySelector('[data-mixer-switch="solo"]'),iem=first.querySelector('[data-mixer-switch="iem"]'),fader=first.querySelector('[data-mixer-fader]');mute.click();await wait(80);solo.click();await wait(80);iem.click();await wait(80);fader.value='.64';fader.dispatchEvent(new Event('input',{bubbles:true}));await wait(120);document.querySelector('#play').click();await wait(900);const state=await window.playback.performance.get();return{channels:document.querySelectorAll('.daw-channel:not(.master)').length,master:!!document.querySelector('.daw-channel.master'),labels:[...document.querySelectorAll('.daw-channel:not(.master) .channel-head strong')].map(x=>x.textContent),gain:state.mixer.channels[0].gain,muted:state.mixer.channels[0].muted,solo:state.mixer.channels[0].solo,iem:state.mixer.channels[0].iem,meterHeights:[...document.querySelectorAll('.meter-fill')].map(x=>x.style.height),iemStatus:document.querySelector('#mixerIemStatus').textContent};})()`);console.log(`MIXER_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_E2E_EDIT){await new Promise(resolveDelay=>setTimeout(resolveDelay,700));const result=await window.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));document.querySelector('#editMode').click();for(let i=0;i<100&&document.querySelector('#draftState').textContent==='LOADING';i++)await wait(100);document.querySelector('#stemsView').click();await wait(100);const selector=document.querySelector('#arrangementSelect'),before=await window.playback.arrange.get(),target=before.sections[1],mid=(target.startSeconds+target.endSeconds)/2;await window.playback.arrange.command({type:'split-section',atSeconds:mid,newSectionId:'e2e-split'});await window.playback.arrange.command({type:'rename-section',sectionId:'e2e-split',name:'E2E Chorus'});await window.playback.arrange.command({type:'duplicate-section',sectionId:'e2e-split',newSectionId:'e2e-duplicate'});await window.playback.arrange.command({type:'move-section',sectionId:'e2e-duplicate',toIndex:0});await window.playback.arrange.command({type:'delete-section',sectionId:target.id});await window.playback.arrange.command({type:'set-key-tempo',key:'D',bpm:80});const after=await window.playback.arrange.workspace();await window.playback.arrange.undo();const undone=await window.playback.arrange.get();await window.playback.arrange.redo();const redone=await window.playback.arrange.get();return{editVisible:!document.querySelector('#editorWorkspace').hidden,modeLabel:document.querySelector('#modeLabel').textContent,selectedArrangement:selector.selectedOptions[0].textContent,arrangementOptions:[...selector.options].map(option=>option.textContent),summaryCanvas:!!document.querySelector('#summaryWaveform canvas'),expandedVisible:!document.querySelector('#stemWaveforms').hidden,stemRows:document.querySelectorAll('.stem-row').length,regionListRows:document.querySelectorAll('.region-list-item').length,source:document.querySelector('#editorSource').textContent,version:document.querySelector('#editorVersion').textContent,beforeSections:before.sections.length,afterSections:after.draft.sections.length,firstSection:after.draft.sections[0].id,editedName:after.draft.sections.find(x=>x.id==='e2e-split').name,key:after.draft.selectedKey,bpm:after.draft.selectedBpm,cueIntegrity:after.draft.cues.every(c=>after.draft.sections.find(s=>s.id===c.targetRegionId)?.name===c.phrase),midiEvents:after.draft.midi.length,readiness:after.readiness.status,checks:after.readiness.checks.length,dirty:after.dirty,undoRevision:undone.revision,redoRevision:redone.revision};})()`);console.log(`EDITOR_WORKSPACE_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if(process.env.PLAYBACK_DEMO_PANIC){await new Promise((resolveDelay)=>setTimeout(resolveDelay,1200));void window.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));document.querySelector('#play').click();await wait(3000);document.querySelector('#panic').click();await wait(2500);document.querySelector('.region:nth-child(3)').click();})()`);}
  if(process.env.PLAYBACK_E2E){await new Promise((resolveDelay)=>setTimeout(resolveDelay,700));const result=await window.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms??120));const click=async selector=>{document.querySelector(selector).click();await wait();};const arrangement=document.querySelector('.arrangement-tools select').selectedOptions[0].textContent,arrangementOptions=[...document.querySelector('.arrangement-tools select').options].map(x=>x.textContent),importAvailable=!document.querySelector('.arrangement-tools button').disabled,initial=document.querySelector('#currentSection').textContent;await click('#nextSection');window.playback.command('seek',25.5);await wait(180);const next=document.querySelector('#currentSection').textContent;await click('#play');await wait(250);const beforePanic=document.querySelector('#clock').textContent;await click('#panic');await wait(350);const duringPanic=document.querySelector('#clock').textContent,panicVisible=!document.querySelector('#panicState').hidden,state=await window.playback.performance.get(),clickAlive=state.channels.click,padAlive=state.channels.pad;await click('.region:nth-child(3)');const recoveryArmed=document.querySelector('#panicState span').textContent;await wait(2200);const recovered=document.querySelector('#panicState').hidden,recoverySection=document.querySelector('#currentSection').textContent;return{ready:document.querySelector('#ready').textContent,arrangement,arrangementOptions,importAvailable,initial,next,beforePanic,duringPanic,panicVisible,clickAlive,padAlive,recoveryArmed,recovered,recoverySection};})()`);console.log(`PERFORMANCE_E2E ${JSON.stringify(result)}`);app.quit();return;}
  if (process.env.PLAYBACK_SCREENSHOT) {
    await new Promise((resolveDelay) => setTimeout(resolveDelay, 1200));
    if (process.env.PLAYBACK_SCREENSHOT_MODE === "performance") await window.webContents.executeJavaScript("document.querySelector('#performanceMode').click()");
    if (process.env.PLAYBACK_SCREENSHOT_MODE === "edit") await window.webContents.executeJavaScript("(async()=>{document.querySelector('#editMode').click();for(let i=0;i<100&&document.querySelector('#draftState').textContent==='LOADING';i++)await new Promise(r=>setTimeout(r,100));})()");
    if (process.env.PLAYBACK_SCREENSHOT_MODE === "prep") await window.webContents.executeJavaScript("(async()=>{document.querySelector('#prepMode').click();for(let i=0;i<100&&!document.querySelectorAll('#preparedLibrary article').length;i++)await new Promise(r=>setTimeout(r,100));})()");
    if (process.env.PLAYBACK_SCREENSHOT_MODE === "remote") await window.webContents.executeJavaScript("document.querySelector('#remoteControl').click()");
    if (process.env.PLAYBACK_SCREENSHOT_MODE === "mixer") await window.webContents.executeJavaScript("(async()=>{window.playback.command('seek',20);await new Promise(r=>setTimeout(r,100));document.querySelector('#play').click();await new Promise(r=>setTimeout(r,900));})()");
    if (process.env.PLAYBACK_SCREENSHOT_VIEW === "stems") await window.webContents.executeJavaScript("document.querySelector('#stemsView').click()");
    await new Promise((resolveDelay) => setTimeout(resolveDelay, 250));
    const image = await window.webContents.capturePage();
    const screenshotPath = resolve(projectRoot, process.env.PLAYBACK_SCREENSHOT);
    await mkdir(resolve(screenshotPath, ".."), { recursive: true });
    await writeFile(screenshotPath, image.toPNG());
    app.quit();
  }
}

app.whenReady().then(createWindow).catch((error) => { console.error(error); app.quit(); });
app.on("window-all-closed", () => app.quit());
app.on("before-quit", () => { if (statusTimer) clearInterval(statusTimer); engine.close();void remoteServer?.close(); });
function listMidiOutputs():Promise<string[]>{return new Promise((resolveList,reject)=>execFile(enginePath,["--list-midi"],{windowsHide:true},(error,stdout)=>error?reject(error):resolveList(stdout.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))));}
function listAudioDevices():Promise<NativeAudioDeviceSelection[]>{return new Promise((resolveList,reject)=>execFile(enginePath,["--list-audio-devices"],{windowsHide:true},(error,stdout)=>error?reject(error):resolveList(stdout.split(/\r?\n/).map(line=>line.split("\t")).filter(parts=>parts.length===2).map(([type,name])=>({type:type!,name:name!})))));}
function sameAudioDevice(left:NativeAudioDeviceSelection,right:NativeAudioDeviceSelection):boolean{return left.type===right.type&&left.name===right.name;}
async function listMidiInputs():Promise<string[]>{return new Promise((resolveList,reject)=>execFile(enginePath,["--list-midi-inputs"],{windowsHide:true},(error,stdout)=>error?reject(error):resolveList(stdout.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))));}
async function saveDeviceSettings():Promise<void>{await mkdir(join(projectRoot,".playback-data"),{recursive:true});await writeFile(join(projectRoot,".playback-data","device-settings.json"),JSON.stringify({midiOutputName:selectedMidiOutput,midiInputName:selectedMidiInput,audioDevice:selectedAudioDevice,audioRouting:selectedAudioRouting,updatedAt:new Date().toISOString()},null,2));}
function defaultAudioRouting(stemCount:number):NativeAudioRouting{return{stems:Array.from({length:stemCount},(_,index)=>index+1),stemChannels:Array.from({length:stemCount},()=>1 as const),click:19,cue:20,pad:21,iem:31};}
function validateAudioRouting(routing:NativeAudioRouting,stemCount:number):void{if(!routing||!Array.isArray(routing.stems)||routing.stems.length!==stemCount||!Array.isArray(routing.stemChannels)||routing.stemChannels.length!==stemCount)throw new Error("Routing must include every prepared stem");const validate=(label:string,start:number,width:number)=>{if(!Number.isInteger(start)||start<0||start>32||(start>0&&start+width-1>32))throw new Error(`${label} must be unassigned or routed within Dante outputs 1-32`);};routing.stems.forEach((output,index)=>{const width=routing.stemChannels[index];if(width!==1&&width!==2)throw new Error(`Stem ${index+1} must be mono or stereo`);validate(`Stem ${index+1}`,output,width);});validate("Click",routing.click,1);validate("Cues",routing.cue,1);validate("Pad",routing.pad,1);validate("IEM",routing.iem,1);}
function testMidiOutput(name:string):Promise<void>{return new Promise((resolveTest,reject)=>execFile(enginePath,["--test-midi-output",name],{windowsHide:true},error=>error?reject(error):resolveTest()));}
function sendMidiBytes(name:string,bytes:readonly number[]):Promise<void>{return new Promise((resolveSend,reject)=>execFile(enginePath,["--send-midi-output",name,...bytes.map(value=>value.toString(16).padStart(2,"0"))],{windowsHide:true},error=>error?reject(error):resolveSend()));}
type ControlSettings={token:string;httpPort:number;oscPort:number;lanEnabled:boolean;oscEnabled:boolean;footControllerProfile:FootControllerProfileId;gld:{host:string;port:number;midiChannel:number;midiOutputName:string|null;writesEnabled:boolean};updatedAt:string};
async function loadOrCreateControlSettings():Promise<ControlSettings>{const path=join(projectRoot,".playback-data","control-settings.json");try{const value=JSON.parse(await readFile(path,"utf8"));if(typeof value.token==="string"&&value.token.length>=16)return{token:value.token,httpPort:Number.isInteger(value.httpPort)?value.httpPort:38191,oscPort:Number.isInteger(value.oscPort)?value.oscPort:38192,lanEnabled:value.lanEnabled===true,oscEnabled:value.oscEnabled!==false,footControllerProfile:value.footControllerProfile==="basic-notes"?"basic-notes":"disabled",gld:{host:typeof value.gld?.host==="string"?value.gld.host:"",port:51325,midiChannel:Number.isInteger(value.gld?.midiChannel)?value.gld.midiChannel:1,midiOutputName:typeof value.gld?.midiOutputName==="string"?value.gld.midiOutputName:null,writesEnabled:false},updatedAt:typeof value.updatedAt==="string"?value.updatedAt:new Date().toISOString()};}catch{}const settings:ControlSettings={token:randomBytes(24).toString("base64url"),httpPort:38191,oscPort:38192,lanEnabled:false,oscEnabled:true,footControllerProfile:"disabled",gld:{host:"",port:51325,midiChannel:1,midiOutputName:null,writesEnabled:false},updatedAt:new Date().toISOString()};await writeControlSettings(settings);return settings;}
async function writeControlSettings(settings:ControlSettings):Promise<void>{await mkdir(join(projectRoot,".playback-data"),{recursive:true});await writeFile(join(projectRoot,".playback-data","control-settings.json"),JSON.stringify(settings,null,2));}
function controlUrls(settings:ControlSettings,address:RemoteControlAddress|null):string[]{if(!address)return[];const hosts=settings.lanEnabled?Object.values(networkInterfaces()).flatMap(items=>(items??[]).filter(item=>item.family==="IPv4"&&!item.internal).map(item=>item.address)):["127.0.0.1"];return[...new Set(hosts)].map(host=>`http://${host}:${address.httpPort}/?token=${encodeURIComponent(settings.token)}`);}
function toPlaybackCommand(value:any):PlaybackCommand{if(value.action==="play")return{type:"transport.play"};if(value.action==="pause")return{type:"transport.pause"};if(value.action==="stop")return{type:"transport.stop"};if(value.action==="panic")return{type:"panic.enter"};if(value.action==="recover")return{type:"panic.recover",regionId:value.regionId};if(value.action==="jump")return{type:"section.jump",regionId:value.regionId};if(value.action==="next-section")return{type:"section.next"};if(value.action==="previous-section")return{type:"section.previous"};if(value.action==="loop")return{type:"section.loop",regionId:value.regionId??performance!.snapshot.currentRegionId??""};if(value.action==="repeat-once")return{type:"section.repeat-once",regionId:value.regionId??performance!.snapshot.currentRegionId??""};if(value.action==="cue-next")return{type:"song.cue-next"};if(value.action==="bus")return{type:"bus.set",bus:value.bus,enabled:value.enabled};if(value.action==="gain")return{type:"bus.gain",bus:value.bus,gain:value.gain};if(value.action==="mixer-channel")return{type:"mixer.channel",index:value.index,gain:value.gain,muted:value.muted,solo:value.solo,iem:value.iem};if(value.action==="mixer-master")return{type:"mixer.master",gain:value.gain};if(value.action==="song")return{type:"song.select",index:value.index};throw new Error("Unknown performance command");}
async function listPreparedArrangements(active:ConfirmedSetManifest):Promise<{name:string;path:string}[]>{const result=[{name:"Original Song",path:originalManifestPath}];try{const{readdir}=await import("node:fs/promises");for(const directory of await readdir(join(projectRoot,".playback-cache","arrangements"),{withFileTypes:true})){if(!directory.isDirectory())continue;const path=join(projectRoot,".playback-cache","arrangements",directory.name,"performance","confirmed-set.json");try{const prepared=JSON.parse(await readFile(path,"utf8"));if(prepared.songs?.[0]?.song?.id===active.songs[0]?.song.id)result.push({name:prepared.name??directory.name,path});}catch{}}}catch{}return result.filter((item,index,array)=>array.findIndex(other=>other.path===item.path)===index);}
async function allPreparedManifestPaths():Promise<string[]>{const paths=[originalManifestPath];try{const{readdir}=await import("node:fs/promises");for(const directory of await readdir(join(projectRoot,".playback-cache","arrangements"),{withFileTypes:true}))if(directory.isDirectory())paths.push(join(projectRoot,".playback-cache","arrangements",directory.name,"performance","confirmed-set.json"));}catch{}return paths;}
function sendToRenderer(channel:string,payload:unknown):void{if(!window||window.isDestroyed()||window.webContents.isDestroyed())return;window.webContents.send(channel,payload);}
function safeCacheName(value:string){const normalized=value.replace(/[^a-z0-9._-]+/gi,"-").replace(/^-|-$/g,"")||"song";return normalized.length<=72?normalized:`${normalized.slice(0,32)}-${normalized.slice(-32)}`;}
function isPreparedManifestPath(path:string):boolean{const cacheRoot=resolve(projectRoot,".playback-cache"),rel=relative(cacheRoot,path);return rel!==""&&!rel.startsWith("..")&&!isAbsolute(rel)&&path.toLowerCase().endsWith("confirmed-set.json");}
function padKey(key:string){const aliases:Record<string,string>={"C#":"Db","D#":"Eb","F#":"Gb","G#":"Ab","A#":"Bb"};return aliases[key]??key;}
async function cuePreviewData(label:string,song:any):Promise<string>{const existing=song.liveAssets?.cues?.find((cue:any)=>cue.label===label)?.audioPath;if(existing)return`data:audio/wav;base64,${(await readFile(existing)).toString("base64")}`;const normalized=label.replace(/([A-Za-z])([0-9])$/,"$1 $2").replace(/^Turnaround/i,"Turn Around"),aliases:Record<string,string>={START:"CountIn.wav"},names=[aliases[normalized.toUpperCase()]??`${normalized.toUpperCase()}.wav`,`${normalized.toUpperCase().replace(/\s+/g,"")}.wav`];for(const name of names){const path=join(productionDefaults.cueFolder,name);try{return`data:audio/wav;base64,${(await readFile(path)).toString("base64")}`;}catch{}}const match=normalized.match(/^(.*)\s+([1-6])$/);if(!match)throw new Error(`No cue audio for ${label}`);const numbers=["ZERO","ONE","TWO","THREE","FOUR","FIVE","SIX"],base=join(productionDefaults.cueFolder,`${match[1]!.toUpperCase()}.wav`),number=join(productionDefaults.cueFolder,`${numbers[Number(match[2])]}.wav`);const bytes=await new Promise<Buffer>((resolveBytes,reject)=>execFile("ffmpeg",["-hide_banner","-loglevel","error","-i",base,"-i",number,"-filter_complex","[0:a][1:a]concat=n=2:v=0:a=1[out]","-map","[out]","-f","wav","pipe:1"],{encoding:"buffer",maxBuffer:16*1024*1024},(error,stdout)=>error?reject(error):resolveBytes(stdout as Buffer)));return`data:audio/wav;base64,${bytes.toString("base64")}`;}
